In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel("wdi2018.xlsx")

In [3]:
data

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%) [SG.VAW.REAS.ZS],Women who believe a husband is justified in beating his wife when she argues with him (%) [SG.VAW.ARGU.ZS],Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS],Women who believe a husband is justified in beating his wife when she goes out without telling him (%) [SG.VAW.GOES.ZS],Women who believe a husband is justified in beating his wife when she neglects the children (%) [SG.VAW.NEGL.ZS],Women who believe a husband is justified in beating his wife when she refuses sex with him (%) [SG.VAW.REFU.ZS],Women who were first married by age 15 (% of women ages 20-24) [SP.M15.2024.FE.ZS],Women who were first married by age 18 (% of women ages 20-24) [SP.M18.2024.FE.ZS],Women's share of population ages 15+ living with HIV (%) [SH.DYN.AIDS.FE.ZS],Young people (ages 15-24) newly infected with HIV [SH.HIV.INCD.YG]
0,2018,YR2018,Afghanistan,AFG,30.9,13.85,81.6,96.616135,95.586174,99.626022,...,..,..,..,..,..,..,..,..,29,500
1,2018,YR2018,Albania,ALB,79.8,62.5,92.2,100,100,100,...,6.8,1.8,0.8,3.7,5.2,0.9,1.4,11.8,25.9,100
2,2018,YR2018,Algeria,DZA,99.6,98.7,100,99.697838,99.071304,99.933952,...,..,..,..,..,..,..,..,..,46.5,500
3,2018,YR2018,American Samoa,ASM,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,2018,YR2018,Andorra,AND,100,100,100,100,100,100,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2018,YR2018,Sub-Saharan Africa,SSF,16.250483,5.54069,32.865363,46.267489,26.955024,73.688568,...,..,..,..,..,..,..,..,..,60.654807,..
262,2018,YR2018,Sub-Saharan Africa (excluding high income),SSA,16.243064,5.534628,32.856981,46.262729,26.948988,73.684042,...,..,..,..,..,..,..,..,..,60.654807,..
263,2018,YR2018,Sub-Saharan Africa (IDA & IBRD countries),TSS,16.250483,5.54069,32.865363,46.267489,26.955024,73.688568,...,..,..,..,..,..,..,..,..,60.654807,..
264,2018,YR2018,Upper middle income,UMC,81.734674,63.792109,91.377499,99.238818,98.74761,99.622869,...,..,..,..,..,..,..,..,..,..,..
265,2018,YR2018,World,WLD,67.051055,44.034131,85.610808,89.478902,83.108318,97.394112,...,..,..,..,..,..,..,..,..,53.6,480000

In [4]:
data = data.replace(to_replace='..', value=np.NaN)

In [5]:
data

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%) [SG.VAW.REAS.ZS],Women who believe a husband is justified in beating his wife when she argues with him (%) [SG.VAW.ARGU.ZS],Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS],Women who believe a husband is justified in beating his wife when she goes out without telling him (%) [SG.VAW.GOES.ZS],Women who believe a husband is justified in beating his wife when she neglects the children (%) [SG.VAW.NEGL.ZS],Women who believe a husband is justified in beating his wife when she refuses sex with him (%) [SG.VAW.REFU.ZS],Women who were first married by age 15 (% of women ages 20-24) [SP.M15.2024.FE.ZS],Women who were first married by age 18 (% of women ages 20-24) [SP.M18.2024.FE.ZS],Women's share of population ages 15+ living with HIV (%) [SH.DYN.AIDS.FE.ZS],Young people (ages 15-24) newly infected with HIV [SH.HIV.INCD.YG]
0,2018,YR2018,Afghanistan,AFG,30.900000,13.850000,81.600000,96.616135,95.586174,99.626022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,500.0
1,2018,YR2018,Albania,ALB,79.800000,62.500000,92.200000,100.000000,100.000000,100.000000,...,6.8,1.8,0.8,3.7,5.2,0.9,1.4,11.8,25.900000,100.0
2,2018,YR2018,Algeria,DZA,99.600000,98.700000,100.000000,99.697838,99.071304,99.933952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.500000,500.0
3,2018,YR2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,YR2018,Andorra,AND,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2018,YR2018,Sub-Saharan Africa,SSF,16.250483,5.540690,32.865363,46.267489,26.955024,73.688568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
262,2018,YR2018,Sub-Saharan Africa (excluding high income),SSA,16.243064,5.534628,32.856981,46.262729,26.948988,73.684042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
263,2018,YR2018,Sub-Saharan Africa (IDA & IBRD countries),TSS,16.250483,5.540690,32.865363,46.267489,26.955024,73.688568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
264,2018,YR2018,Upper middle income,UMC,81.734674,63.792109,91.377499,99.238818,98.747610,99.622869,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,2018,YR2018,World,WLD,67.051055,44.034131,85.610808,89.478902,83.108318,97.394112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.600000,480000.0

In [6]:
#% of missing values per column 

#Because division of sum by length is mean, you can instead df_missing.sum()/len(df) use df_missing.mean()
result = data.isna().mean()

In [7]:
print(result)

Time                                                                                                               0.000000
Time Code                                                                                                          0.000000
Country Name                                                                                                       0.000000
Country Code                                                                                                       0.000000
Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]                              0.109023
                                                                                                                     ...
Women who believe a husband is justified in beating his wife when she refuses sex with him (%) [SG.VAW.REFU.ZS]    0.958647
Women who were first married by age 15 (% of women ages 20-24) [SP.M15.2024.FE.ZS]                                 0.890977
Women who were first married by age 18 (% of women ages 20-24) [SP.M18.2024.FE.ZS]                                 0.890977
Women's share of population ages 15+ living with HIV (%) [SH.DYN.AIDS.FE.ZS]                                       0.259398
Young people (ages 15-24) newly infected with HIV [SH.HIV.INCD.YG]                                                 0.503759
Length: 1446, dtype: float64

In [8]:
#remove columns with >05% NA
data_filtered95 = data.loc[:,result < .05]
#print(list(data_filtered95.columns))

#print(len(list(data_filtered95.columns)))

In [9]:
#remove columns with >10% NA
data_filtered90 = data.loc[:,result < .1]
#print(list(data_filtered90.columns))

#print(len(list(data_filtered90.columns)))

In [10]:
#remove columns with >20% NA
data_filtered80 = data.loc[:,result < .2]
#print(list(data_filtered80.columns))

print(len(list(data_filtered80.columns)))

448

In [11]:
data_filtered80.head()

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Urban population [SP.URB.TOTL],Urban population (% of total population) [SP.URB.TOTL.IN.ZS],Urban population growth (annual %) [SP.URB.GROW],"Vulnerable employment, female (% of female employment) (modeled ILO estimate) [SL.EMP.VULN.FE.ZS]","Vulnerable employment, male (% of male employment) (modeled ILO estimate) [SL.EMP.VULN.MA.ZS]","Vulnerable employment, total (% of total employment) (modeled ILO estimate) [SL.EMP.VULN.ZS]","Wage and salaried workers, female (% of female employment) (modeled ILO estimate) [SL.EMP.WORK.FE.ZS]","Wage and salaried workers, male (% of male employment) (modeled ILO estimate) [SL.EMP.WORK.MA.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]","Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal) [ER.GDP.FWTL.M3.KD]"
0,2018,YR2018,Afghanistan,AFG,30.9,13.85,81.6,96.616135,95.586174,99.626022,...,9353296.0,25.495,3.850833,89.920004,76.949996,79.619999,7.870000,20.200001,17.660000,1.047290
1,2018,YR2018,Albania,ALB,79.8,62.50,92.2,100.000000,100.000000,100.000000,...,1728969.0,60.319,1.317162,51.700001,52.540001,52.190001,47.020000,42.730000,44.520000,13.259350
2,2018,YR2018,Algeria,DZA,99.6,98.70,100.0,99.697838,99.071304,99.933952,...,30451166.0,72.629,2.700947,23.400001,28.090001,27.349999,74.580002,66.790001,68.019997,17.914671
3,2018,YR2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,42203.0,87.153,-2.142604,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,YR2018,Andorra,AND,100.0,100.00,100.0,100.000000,100.000000,100.000000,...,66058.0,88.062,1.480831,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
list(data_filtered80.columns)

['Time',
 'Time Code',
 'Country Name',
 'Country Code',
 'Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]',
 'Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]',
 'Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]',
 'Access to electricity (% of population) [EG.ELC.ACCS.ZS]',
 'Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]',
 'Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]',
 'Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]',
 'Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]',
 'Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS]',
 'Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS]',
 'Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]',
 'Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS]',
 'Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS]',
 'Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD]',
 'Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS]',
 'Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS]',
 'Adjusted savings: particulate emission damage (% of GNI) [NY.ADJ.DPEM.GN.ZS]',
 'Adolescent fertility rate (births per 1,000 women ages 15-19) [SP.ADO.TFRT]',
 'Age dependency ratio (% of working-age population) [SP.POP.DPND]',
 'Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]',
 'Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]',
 'Agricultural land (% of land area) [AG.LND.AGRI.ZS]',
 'Agricultural land (sq. km) [AG.LND.AGRI.K2]',
 'Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]',
 'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]',
 'Agriculture, forestry, and fishing, value added (% of GDP) [NV.AGR.TOTL.ZS]',
 'Agriculture, forestry, and fishing, value added (annual % growth) [NV.AGR.TOTL.KD.ZG]',
 'Agriculture, forestry, and fishing, value added (constant 2015 US$) [NV.AGR.TOTL.KD]',
 'Agriculture, forestry, and fishing, value added (current US$) [NV.AGR.TOTL.CD]',
 'Agriculture, forestry, and fishing, value added per worker (constant 2015 US$) [NV.AGR.EMPL.KD]',
 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal) [ER.H2O.FWAG.ZS]',
 'Annual freshwater withdrawals, domestic (% of total freshwater withdrawal) [ER.H2O.FWDM.ZS]',
 'Annual freshwater withdrawals, industry (% of total freshwater withdrawal) [ER.H2O.FWIN.ZS]',
 'Annual freshwater withdrawals, total (% of internal resources) [ER.H2O.FWTL.ZS]',
 'Annual freshwater withdrawals, total (billion cubic meters) [ER.H2O.FWTL.K3]',
 'Aquaculture production (metric tons) [ER.FSH.AQUA.MT]',
 'Arable land (% of land area) [AG.LND.ARBL.ZS]',
 'Arable land (hectares per person) [AG.LND.ARBL.HA.PC]',
 'Armed forces personnel, total [MS.MIL.TOTL.P1]',
 'Automated teller machines (ATMs) (per 100,000 adults) [FB.ATM.TOTL.P5]',
 'Bird species, threatened [EN.BIR.THRD.NO]',
 'Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]',
 'Business extent of disclosure index (0=less disclosure to 10=more disclosure) [IC.BUS.DISC.XQ]',
 'Capture fisheries production (metric tons) [ER.FSH.CAPT.MT]',
 'Cereal production (metric tons) [AG.PRD.CREL.MT]',
 'Cereal yield (kg per hectare) [AG.YLD.CREL.KG]',
 'Claims on central government, etc. (% GDP) [FS.AST.CGOV.GD.ZS]',
 'CO2 emissions (kg per 2015 US$ of GDP) [EN.ATM.CO2E.KD.GD]',
 'CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]',
 'CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD]',
 'CO2 emissions (kt) [EN.ATM.CO2E.KT]',
 'CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]',
 'Coal rents (% of GDP) [NY.GDP.COAL.RT.ZS]',
 'Commercial bank branches (per 100,000 adults) [FB.CBK.BRCH.P5]',
 'Commercial service exports (current US$) [TX.VAL.SERV.CD.WT]',
 'Commercial service imports (current US$) [TM.VAL.SERV.CD.WT]',
 'Communications, computer, etc. (% of service exports, BoP) [BX.GSR.CMCP.ZS]',
 'Communications, computer, etc. (% of service imports, BoP) [BM.GSR.CMCP.ZS]',
 'Compulsory education, duration (years) [SE.COM.DURS]',
 'Computer, communications and other services (% of commercial service exports) [TX.VAL.OTHR.ZS.WT]',
 'Computer, communications and other services (% of commercial service imports) [TM.VAL.OTHR.ZS.WT]',
 'Contributing family workers, female (% of female employment) (modeled ILO estimate) [SL.FAM.WORK.FE.ZS]',
 'Contributing family workers, male (% of male employment) (modeled ILO estimate) [SL.FAM.WORK.MA.ZS]',
 'Contributing family workers, total (% of total employment) (modeled ILO estimate) [SL.FAM.WORK.ZS]',
 'Cost of business start-up procedures (% of GNI per capita) [IC.REG.COST.PC.ZS]',
 'Cost of business start-up procedures, female (% of GNI per capita) [IC.REG.COST.PC.FE.ZS]',
 'Cost of business start-up procedures, male (% of GNI per capita) [IC.REG.COST.PC.MA.ZS]',
 'Cost to export, border compliance (US$) [IC.EXP.CSBC.CD]',
 'Cost to export, documentary compliance (US$) [IC.EXP.CSDC.CD]',
 'Cost to import, border compliance (US$) [IC.IMP.CSBC.CD]',
 'Cost to import, documentary compliance (US$) [IC.IMP.CSDC.CD]',
 'Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS]',
 'Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD]',
 'Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]',
 'Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]',
 'DEC alternative conversion factor (LCU per US$) [PA.NUS.ATLS]',
 'Depth of credit information index (0=low to 8=high) [IC.CRD.INFO.XQ]',
 'Domestic credit to private sector (% of GDP) [FS.AST.PRVT.GD.ZS]',
 'Domestic credit to private sector by banks (% of GDP) [FD.AST.PRVT.GD.ZS]',
 'Domestic general government health expenditure (% of current health expenditure) [SH.XPD.GHED.CH.ZS]',
 'Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS]',
 'Domestic general government health expenditure per capita (current US$) [SH.XPD.GHED.PC.CD]',
 'Domestic general government health expenditure per capita, PPP (current international $) [SH.XPD.GHED.PP.CD]',
 'Domestic private health expenditure (% of current health expenditure) [SH.XPD.PVTD.CH.ZS]',
 'Domestic private health expenditure per capita (current US$) [SH.XPD.PVTD.PC.CD]',
 'Domestic private health expenditure per capita, PPP (current international $) [SH.XPD.PVTD.PP.CD]',
 'Ease of doing business score (0 = lowest performance to 100 = best performance) [IC.BUS.DFRN.XQ]',
 'Employers, female (% of female employment) (modeled ILO estimate) [SL.EMP.MPYR.FE.ZS]',
 'Employers, male (% of male employment) (modeled ILO estimate) [SL.EMP.MPYR.MA.ZS]',
 'Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]',
 'Employment in agriculture (% of total employment) (modeled ILO estimate) [SL.AGR.EMPL.ZS]',
 'Employment in agriculture, female (% of female employment) (modeled ILO estimate) [SL.AGR.EMPL.FE.ZS]',
 'Employment in agriculture, male (% of male employment) (modeled ILO estimate) [SL.AGR.EMPL.MA.ZS]',
 'Employment in industry (% of total employment) (modeled ILO estimate) [SL.IND.EMPL.ZS]',
 'Employment in industry, female (% of female employment) (modeled ILO estimate) [SL.IND.EMPL.FE.ZS]',
 'Employment in industry, male (% of male employment) (modeled ILO estimate) [SL.IND.EMPL.MA.ZS]',
 'Employment in services (% of total employment) (modeled ILO estimate) [SL.SRV.EMPL.ZS]',
 'Employment in services, female (% of female employment) (modeled ILO estimate) [SL.SRV.EMPL.FE.ZS]',
 'Employment in services, male (% of male employment) (modeled ILO estimate) [SL.SRV.EMPL.MA.ZS]',
 'Employment to population ratio, 15+, female (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.FE.ZS]',
 'Employment to population ratio, 15+, male (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.MA.ZS]',
 'Employment to population ratio, 15+, total (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.ZS]',
 'Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate) [SL.EMP.1524.SP.FE.ZS]',
 'Employment to population ratio, ages 15-24, male (%) (modeled ILO estimate) [SL.EMP.1524.SP.MA.ZS]',
 'Employment to population ratio, ages 15-24, total (%) (modeled ILO estimate) [SL.EMP.1524.SP.ZS]',
 'Exports of goods and services (% of GDP) [NE.EXP.GNFS.ZS]',
 'Exports of goods and services (BoP, current US$) [BX.GSR.GNFS.CD]',
 'Exports of goods and services (current US$) [NE.EXP.GNFS.CD]',
 'Exports of goods, services and primary income (BoP, current US$) [BX.GSR.TOTL.CD]',
 'External balance on goods and services (% of GDP) [NE.RSB.GNFS.ZS]',
 'External health expenditure (% of current health expenditure) [SH.XPD.EHEX.CH.ZS]',
 'External health expenditure per capita (current US$) [SH.XPD.EHEX.PC.CD]',
 'External health expenditure per capita, PPP (current international $) [SH.XPD.EHEX.PP.CD]',
 'Fertility rate, total (births per woman) [SP.DYN.TFRT.IN]',
 'Final consumption expenditure (current US$) [NE.CON.TOTL.CD]',
 'Fish species, threatened [EN.FSH.THRD.NO]',
 'Fixed broadband subscriptions [IT.NET.BBND]',
 'Fixed broadband subscriptions (per 100 people) [IT.NET.BBND.P2]',
 'Fixed telephone subscriptions [IT.MLT.MAIN]',
 'Fixed telephone subscriptions (per 100 people) [IT.MLT.MAIN.P2]',
 'Foreign direct investment, net inflows (% of GDP) [BX.KLT.DINV.WD.GD.ZS]',
 'Foreign direct investment, net inflows (BoP, current US$) [BX.KLT.DINV.CD.WD]',
 'Foreign direct investment, net outflows (% of GDP) [BM.KLT.DINV.WD.GD.ZS]',
 'Foreign direct investment, net outflows (BoP, current US$) [BM.KLT.DINV.CD.WD]',
 'Forest area (% of land area) [AG.LND.FRST.ZS]',
 'Forest area (sq. km) [AG.LND.FRST.K2]',
 'Forest rents (% of GDP) [NY.GDP.FRST.RT.ZS]',
 'GDP (constant 2015 US$) [NY.GDP.MKTP.KD]',
 'GDP (current US$) [NY.GDP.MKTP.CD]',
 'GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
 'GDP per capita (constant 2015 US$) [NY.GDP.PCAP.KD]',
 'GDP per capita (current US$) [NY.GDP.PCAP.CD]',
 'GDP per capita growth (annual %) [NY.GDP.PCAP.KD.ZG]',
 'GDP per capita, PPP (constant 2017 international $) [NY.GDP.PCAP.PP.KD]',
 'GDP per capita, PPP (current international $) [NY.GDP.PCAP.PP.CD]',
 'GDP per person employed (constant 2017 PPP $) [SL.GDP.PCAP.EM.KD]',
 'GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]',
 'GDP, PPP (current international $) [NY.GDP.MKTP.PP.CD]',
 'General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]',
 'General government final consumption expenditure (current US$) [NE.CON.GOVT.CD]',
 'GNI (current US$) [NY.GNP.MKTP.CD]',
 'GNI per capita, Atlas method (current US$) [NY.GNP.PCAP.CD]',
 'GNI per capita, PPP (current international $) [NY.GNP.PCAP.PP.CD]',
 'GNI, Atlas method (current US$) [NY.GNP.ATLS.CD]',
 'GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]',
 'Goods exports (BoP, current US$) [BX.GSR.MRCH.CD]',
 'Goods imports (BoP, current US$) [BM.GSR.MRCH.CD]',
 'Government expenditure on education, total (% of GDP) [SE.XPD.TOTL.GD.ZS]',
 'Government expenditure on education, total (% of government expenditure) [SE.XPD.TOTL.GB.ZS]',
 'Gross capital formation (% of GDP) [NE.GDI.TOTL.ZS]',
 'Gross capital formation (current US$) [NE.GDI.TOTL.CD]',
 'Gross domestic savings (% of GDP) [NY.GDS.TOTL.ZS]',
 'Gross domestic savings (current US$) [NY.GDS.TOTL.CD]',
 'Gross fixed capital formation (% of GDP) [NE.GDI.FTOT.ZS]',
 'Gross fixed capital formation (current US$) [NE.GDI.FTOT.CD]',
 'Gross national expenditure (current US$) [NE.DAB.TOTL.CD]',
 'Gross value added at basic prices (GVA) (constant 2015 US$) [NY.GDP.FCST.KD]',
 'Gross value added at basic prices (GVA) (current US$) [NY.GDP.FCST.CD]',
 'Households and NPISHs final consumption expenditure (% of GDP) [NE.CON.PRVT.ZS]',
 'Households and NPISHs Final consumption expenditure (annual % growth) [NE.CON.PRVT.KD.ZG]',
 'Households and NPISHs Final consumption expenditure (current US$) [NE.CON.PRVT.CD]',
 'ICT service exports (% of service exports, BoP) [BX.GSR.CCIS.ZS]',
 'ICT service exports (BoP, current US$) [BX.GSR.CCIS.CD]',
 'Immunization, DPT (% of children ages 12-23 months) [SH.IMM.IDPT]',
 'Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]',
 'Immunization, measles (% of children ages 12-23 months) [SH.IMM.MEAS]',
 'Imports of goods and services (% of GDP) [NE.IMP.GNFS.ZS]',
 'Imports of goods and services (BoP, current US$) [BM.GSR.GNFS.CD]',
 'Imports of goods and services (current US$) [NE.IMP.GNFS.CD]',
 'Imports of goods, services and primary income (BoP, current US$) [BM.GSR.TOTL.CD]',
 'Incidence of tuberculosis (per 100,000 people) [SH.TBS.INCD]',
 'Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]',
 'Industry (including construction), value added (annual % growth) [NV.IND.TOTL.KD.ZG]',
 'Industry (including construction), value added (constant 2015 US$) [NV.IND.TOTL.KD]',
 'Industry (including construction), value added (current US$) [NV.IND.TOTL.CD]',
 'Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]',
 'Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]',
 'Insurance and financial services (% of commercial service exports) [TX.VAL.INSF.ZS.WT]',
 'Insurance and financial services (% of commercial service imports) [TM.VAL.INSF.ZS.WT]',
 'Insurance and financial services (% of service exports, BoP) [BX.GSR.INSF.ZS]',
 'Insurance and financial services (% of service imports, BoP) [BM.GSR.INSF.ZS]',
 'International tourism, expenditures for travel items (current US$) [ST.INT.TVLX.CD]',
 'International tourism, number of arrivals [ST.INT.ARVL]',
 'International tourism, receipts for travel items (current US$) [ST.INT.TVLR.CD]',
 'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate) [SL.TLF.ACTI.1524.FE.ZS]',
 'Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate) [SL.TLF.ACTI.1524.MA.ZS]',
 'Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate) [SL.TLF.ACTI.1524.ZS]',
 'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate) [SL.TLF.CACT.FE.ZS]',
 'Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate) [SL.TLF.ACTI.FE.ZS]',
 'Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate) [SL.TLF.CACT.MA.ZS]',
 'Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate) [SL.TLF.ACTI.MA.ZS]',
 'Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate) [SL.TLF.CACT.ZS]',
 'Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate) [SL.TLF.ACTI.ZS]',
 'Labor force, female (% of total labor force) [SL.TLF.TOTL.FE.ZS]',
 'Labor force, total [SL.TLF.TOTL.IN]',
 'Labor tax and contributions (% of commercial profits) [IC.TAX.LABR.CP.ZS]',
 'Land area (sq. km) [AG.LND.TOTL.K2]',
 'Land under cereal production (hectares) [AG.LND.CREL.HA]',
 'Life expectancy at birth, female (years) [SP.DYN.LE00.FE.IN]',
 'Life expectancy at birth, male (years) [SP.DYN.LE00.MA.IN]',
 'Life expectancy at birth, total (years) [SP.DYN.LE00.IN]',
 'Mammal species, threatened [EN.MAM.THRD.NO]',
 'Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]',
 'Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]',
 'Manufacturing, value added (constant 2015 US$) [NV.IND.MANF.KD]',
 'Manufacturing, value added (current US$) [NV.IND.MANF.CD]',
 'Merchandise exports (current US$) [TX.VAL.MRCH.CD.WT]',
 'Merchandise exports by the reporting economy (current US$) [TX.VAL.MRCH.WL.CD]',
 'Merchandise exports by the reporting economy, residual (% of total merchandise exports) [TX.VAL.MRCH.RS.ZS]',
 'Merchandise exports to economies in the Arab World (% of total merchandise exports) [TX.VAL.MRCH.AL.ZS]',
 'Merchandise exports to high-income economies (% of total merchandise exports) [TX.VAL.MRCH.HI.ZS]',
 'Merchandise exports to low- and middle-income economies in East Asia & Pacific (% of total merchandise exports) [TX.VAL.MRCH.R1.ZS]',
 'Merchandise exports to low- and middle-income economies in Europe & Central Asia (% of total merchandise exports) [TX.VAL.MRCH.R2.ZS]',
 'Merchandise exports to low- and middle-income economies in Latin America & the Caribbean (% of total merchandise exports) [TX.VAL.MRCH.R3.ZS]',
 'Merchandise exports to low- and middle-income economies in Middle East & North Africa (% of total merchandise exports) [TX.VAL.MRCH.R4.ZS]',
 'Merchandise exports to low- and middle-income economies in South Asia (% of total merchandise exports) [TX.VAL.MRCH.R5.ZS]',
 'Merchandise exports to low- and middle-income economies in Sub-Saharan Africa (% of total merchandise exports) [TX.VAL.MRCH.R6.ZS]',
 'Merchandise exports to low- and middle-income economies outside region (% of total merchandise exports) [TX.VAL.MRCH.OR.ZS]',
 'Merchandise imports (current US$) [TM.VAL.MRCH.CD.WT]',
 'Merchandise imports by the reporting economy (current US$) [TM.VAL.MRCH.WL.CD]',
 'Merchandise imports by the reporting economy, residual (% of total merchandise imports) [TM.VAL.MRCH.RS.ZS]',
 'Merchandise imports from economies in the Arab World (% of total merchandise imports) [TM.VAL.MRCH.AL.ZS]',
 'Merchandise imports from high-income economies (% of total merchandise imports) [TM.VAL.MRCH.HI.ZS]',
 'Merchandise imports from low- and middle-income economies in East Asia & Pacific (% of total merchandise imports) [TM.VAL.MRCH.R1.ZS]',
 'Merchandise imports from low- and middle-income economies in Europe & Central Asia (% of total merchandise imports) [TM.VAL.MRCH.R2.ZS]',
 'Merchandise imports from low- and middle-income economies in Latin America & the Caribbean (% of total merchandise imports) [TM.VAL.MRCH.R3.ZS]',
 'Merchandise imports from low- and middle-income economies in Middle East & North Africa (% of total merchandise imports) [TM.VAL.MRCH.R4.ZS]',
 'Merchandise imports from low- and middle-income economies in South Asia (% of total merchandise imports) [TM.VAL.MRCH.R5.ZS]',
 'Merchandise imports from low- and middle-income economies in Sub-Saharan Africa (% of total merchandise imports) [TM.VAL.MRCH.R6.ZS]',
 'Merchandise imports from low- and middle-income economies outside region (% of total merchandise imports) [TM.VAL.MRCH.OR.ZS]',
 'Merchandise trade (% of GDP) [TG.VAL.TOTL.GD.ZS]',
 'Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]',
 'Mineral rents (% of GDP) [NY.GDP.MINR.RT.ZS]',
 'Mobile cellular subscriptions [IT.CEL.SETS]',
 'Mobile cellular subscriptions (per 100 people) [IT.CEL.SETS.P2]',
 'Monetary Sector credit to private sector (% GDP) [FM.AST.PRVT.GD.ZS]',
 'Mortality caused by road traffic injury (per 100,000 population) [SH.STA.TRAF.P5]',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%) [SH.DYN.NCOM.ZS]',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%) [SH.DYN.NCOM.FE.ZS]',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%) [SH.DYN.NCOM.MA.ZS]',
 'Mortality rate attributed to unintentional poisoning (per 100,000 population) [SH.STA.POIS.P5]',
 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population) [SH.STA.POIS.P5.FE]',
 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population) [SH.STA.POIS.P5.MA]',
 'Mortality rate, adult, female (per 1,000 female adults) [SP.DYN.AMRT.FE]',
 'Mortality rate, adult, male (per 1,000 male adults) [SP.DYN.AMRT.MA]',
 'Mortality rate, infant (per 1,000 live births) [SP.DYN.IMRT.IN]',
 'Mortality rate, infant, female (per 1,000 live births) [SP.DYN.IMRT.FE.IN]',

In [13]:
# tentative add metadata

In [14]:
meta_country = pd.read_csv('data\Metadata_Country.csv')

In [15]:
meta_country

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,ABW,Latin America & Caribbean,High income,NaN,Aruba,NaN
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern,NaN
2,AFG,South Asia,Low income,The reporting period for national accounts dat...,Afghanistan,NaN
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central,NaN
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola,NaN
...,...,...,...,...,...,...
260,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo,NaN
261,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep.",NaN
262,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa,NaN
263,ZMB,Sub-Saharan Africa,Low income,National accounts data were rebased to reflect...,Zambia,NaN
264,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe,NaN

In [16]:
meta_country.drop("Unnamed: 5",axis=1)

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,South Asia,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
260,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
261,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
262,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
263,ZMB,Sub-Saharan Africa,Low income,National accounts data were rebased to reflect...,Zambia
264,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [17]:
data

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%) [SG.VAW.REAS.ZS],Women who believe a husband is justified in beating his wife when she argues with him (%) [SG.VAW.ARGU.ZS],Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS],Women who believe a husband is justified in beating his wife when she goes out without telling him (%) [SG.VAW.GOES.ZS],Women who believe a husband is justified in beating his wife when she neglects the children (%) [SG.VAW.NEGL.ZS],Women who believe a husband is justified in beating his wife when she refuses sex with him (%) [SG.VAW.REFU.ZS],Women who were first married by age 15 (% of women ages 20-24) [SP.M15.2024.FE.ZS],Women who were first married by age 18 (% of women ages 20-24) [SP.M18.2024.FE.ZS],Women's share of population ages 15+ living with HIV (%) [SH.DYN.AIDS.FE.ZS],Young people (ages 15-24) newly infected with HIV [SH.HIV.INCD.YG]
0,2018,YR2018,Afghanistan,AFG,30.900000,13.850000,81.600000,96.616135,95.586174,99.626022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,500.0
1,2018,YR2018,Albania,ALB,79.800000,62.500000,92.200000,100.000000,100.000000,100.000000,...,6.8,1.8,0.8,3.7,5.2,0.9,1.4,11.8,25.900000,100.0
2,2018,YR2018,Algeria,DZA,99.600000,98.700000,100.000000,99.697838,99.071304,99.933952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.500000,500.0
3,2018,YR2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,YR2018,Andorra,AND,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2018,YR2018,Sub-Saharan Africa,SSF,16.250483,5.540690,32.865363,46.267489,26.955024,73.688568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
262,2018,YR2018,Sub-Saharan Africa (excluding high income),SSA,16.243064,5.534628,32.856981,46.262729,26.948988,73.684042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
263,2018,YR2018,Sub-Saharan Africa (IDA & IBRD countries),TSS,16.250483,5.540690,32.865363,46.267489,26.955024,73.688568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
264,2018,YR2018,Upper middle income,UMC,81.734674,63.792109,91.377499,99.238818,98.747610,99.622869,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,2018,YR2018,World,WLD,67.051055,44.034131,85.610808,89.478902,83.108318,97.394112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.600000,480000.0