<a href="https://colab.research.google.com/github/isabellacadisco/AMS/blob/main/Missing_value_imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import set_config
set_config(display='diagram')
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("retained_vars.csv")

In [3]:
not_null_income_group = data[data['Income Group'].notna()]

In [4]:
not_null_income_group

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE],Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE],...,"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]","Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]","Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]","Manufacturing, value added (current US$) [NV.IND.MANF.CD]","Population, total [SP.POP.TOTL]",Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS],"Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group
0,AFG,Afghanistan,30.9,13.85,81.6,96.616135,95.586174,99.626022,10540.0,4310.0,...,0.626149,2.071349,6.160177,22.921060,1.134634e+09,36686784.0,71.4,11.110,17.660000,L
1,ALB,Albania,79.8,62.50,92.2,100.000000,100.000000,100.000000,2010.0,960.0,...,2.028060,1.473058,6.133262,6.259229,9.295837e+08,2866376.0,37.3,12.300,44.520000,UM
2,DZA,Algeria,99.6,98.70,100.0,99.697838,99.071304,99.933952,6820.0,5530.0,...,4.269990,6.757341,26.549953,-4.603222,4.643876e+10,41927007.0,66.1,10.416,68.019997,UM
3,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.695361,13.928013,16.867470,8.900000e+07,48424.0,NaN,NaN,NaN,UM
4,AND,Andorra,100.0,100.00,100.0,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,1.012478,3.610284,-2.170767,1.161904e+08,75013.0,NaN,NaN,NaN,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,1.441528,NaN,NaN,NaN,107001.0,NaN,12.245,93.419998,H
213,PSE,West Bank and Gaza,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,-0.195108,-0.301993,11.547252,0.341530,1.879500e+09,4569087.0,15.3,26.260,69.739998,LM
214,YEM,"Yemen, Rep.",61.5,42.90,93.7,62.000000,NaN,NaN,4360.0,2980.0,...,NaN,14.853665,NaN,NaN,NaN,30790513.0,26.6,13.076,45.299999,L
215,ZMB,Zambia,11.9,2.10,24.6,40.317890,12.466436,76.461876,10330.0,13510.0,...,7.494572,7.411571,6.847766,4.071350,1.801756e+09,17835893.0,15.6,5.030,24.860001,LM
216,ZWE,Zimbabwe,29.9,6.40,79.1,45.572647,26.617121,85.468765,6420.0,4660.0,...,10.618866,200.769578,13.678137,1.387913,4.671914e+09,15052184.0,31.6,6.784,32.650002,LM

In [5]:
data_manova = not_null_income_group

In [6]:
retained_var_pol = [
    'Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]',
    'Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]',
    'Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]',
    'Access to electricity (% of population) [EG.ELC.ACCS.ZS]',
    'Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]',
    'Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]',
    'Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]',
    'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]',
    'Annual freshwater withdrawals, total (% of internal resources) [ER.H2O.FWTL.ZS]',
    'CO2 emissions (kg per 2015 US$ of GDP) [EN.ATM.CO2E.KD.GD]',
    'CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]',
    'CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD]',
    'CO2 emissions (kt) [EN.ATM.CO2E.KT]',
    'CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]',
    'Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]',
    'Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]',
    'Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]',
    'Renewable internal freshwater resources per capita (cubic meters) [ER.H2O.INTR.PC]',
    'Renewable internal freshwater resources, total (billion cubic meters) [ER.H2O.INTR.K3]',
    'Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]',    
]

retained_var_ec = [
    'Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]',
    'Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]',
    'Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS]',
    'Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS]',
    'Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]',
    'Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS]',
    'Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS]',
    'Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD]',
    'Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS]',
    'Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS]',
    'Adjusted savings: particulate emission damage (% of GNI) [NY.ADJ.DPEM.GN.ZS]',
    'Age dependency ratio (% of working-age population) [SP.POP.DPND]',
    'Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]',
    'Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]',
    'Contributing family workers, total (% of total employment) (modeled ILO estimate) [SL.FAM.WORK.ZS]',
    'Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]',
    'Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]',
    'Exports of goods and services (% of GDP) [NE.EXP.GNFS.ZS]',
    'Exports of goods and services (current US$) [NE.EXP.GNFS.CD]',
    'Final consumption expenditure (current US$) [NE.CON.TOTL.CD]',
    'GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
    'GDP (current US$) [NY.GDP.MKTP.CD]',
    'GDP per capita (current US$) [NY.GDP.PCAP.CD]',
    'General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]',
    'General government final consumption expenditure (current US$) [NE.CON.GOVT.CD]',
    'GNI (current US$) [NY.GNP.MKTP.CD]',
    'GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]',
    'Imports of goods and services (BoP, current US$) [BM.GSR.GNFS.CD]',
    'Imports of goods and services (current US$) [NE.IMP.GNFS.CD]',
    'Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]',
    'Industry (including construction), value added (annual % growth) [NV.IND.TOTL.KD.ZG]',
    'Industry (including construction), value added (current US$) [NV.IND.TOTL.CD]',
    'Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]',
    'Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]',
    'Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]',
    'Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]',
    'Manufacturing, value added (current US$) [NV.IND.MANF.CD]',
    'Population, total [SP.POP.TOTL]',
    'Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS]',
    'Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]',
    'Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]',
]

In [7]:
from pandas.api.types import CategoricalDtype

category_values = ['H', 'UM', 'LM', 'L']

category_order = CategoricalDtype(category_values, ordered=True)

data_manova.loc[:,'Income Group'] = data_manova.loc[:,'Income Group'].astype(category_order)

<ipython-input-7-732c194f020e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_manova.loc[:,'Income Group'] = data_manova.loc[:,'Income Group'].astype(category_order)

In [8]:
data_manova

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE],Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE],...,"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]","Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]","Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]","Manufacturing, value added (current US$) [NV.IND.MANF.CD]","Population, total [SP.POP.TOTL]",Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS],"Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group
0,AFG,Afghanistan,30.9,13.85,81.6,96.616135,95.586174,99.626022,10540.0,4310.0,...,0.626149,2.071349,6.160177,22.921060,1.134634e+09,36686784.0,71.4,11.110,17.660000,L
1,ALB,Albania,79.8,62.50,92.2,100.000000,100.000000,100.000000,2010.0,960.0,...,2.028060,1.473058,6.133262,6.259229,9.295837e+08,2866376.0,37.3,12.300,44.520000,UM
2,DZA,Algeria,99.6,98.70,100.0,99.697838,99.071304,99.933952,6820.0,5530.0,...,4.269990,6.757341,26.549953,-4.603222,4.643876e+10,41927007.0,66.1,10.416,68.019997,UM
3,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.695361,13.928013,16.867470,8.900000e+07,48424.0,NaN,NaN,NaN,UM
4,AND,Andorra,100.0,100.00,100.0,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,1.012478,3.610284,-2.170767,1.161904e+08,75013.0,NaN,NaN,NaN,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,1.441528,NaN,NaN,NaN,107001.0,NaN,12.245,93.419998,H
213,PSE,West Bank and Gaza,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,-0.195108,-0.301993,11.547252,0.341530,1.879500e+09,4569087.0,15.3,26.260,69.739998,LM
214,YEM,"Yemen, Rep.",61.5,42.90,93.7,62.000000,NaN,NaN,4360.0,2980.0,...,NaN,14.853665,NaN,NaN,NaN,30790513.0,26.6,13.076,45.299999,L
215,ZMB,Zambia,11.9,2.10,24.6,40.317890,12.466436,76.461876,10330.0,13510.0,...,7.494572,7.411571,6.847766,4.071350,1.801756e+09,17835893.0,15.6,5.030,24.860001,LM
216,ZWE,Zimbabwe,29.9,6.40,79.1,45.572647,26.617121,85.468765,6420.0,4660.0,...,10.618866,200.769578,13.678137,1.387913,4.671914e+09,15052184.0,31.6,6.784,32.650002,LM

In [9]:
data_manova['Income Group'].unique()

['L', 'UM', 'H', 'LM']
Categories (4, object): ['H' < 'UM' < 'LM' < 'L']

In [10]:
X = data_manova[retained_var_ec + retained_var_pol]

In [11]:
X

,Adjusted net national income (current US$) [NY.ADJ.NNTY.CD],Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS],Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS],Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS],Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS],Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS],Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD],Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS],Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS],...,CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD],CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD],CO2 emissions (kt) [EN.ATM.CO2E.KT],CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC],Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE],Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE],Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],Renewable internal freshwater resources per capita (cubic meters) [ER.H2O.INTR.PC],"Renewable internal freshwater resources, total (billion cubic meters) [ER.H2O.INTR.K3]",Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]
0,1.681519e+10,458.344566,1.598055,7.417784,2.594447,0.154942,0.000000,0.000000e+00,0.397921,0.242979,...,0.080291,0.078417,6070.000172,0.165455,15909.999850,4690.0,17.96,1285.203958,47.1500,27690.000530
1,1.237962e+10,4318.911492,1.439030,17.030871,3.303909,0.991616,0.018862,2.855307e+06,1.190626,0.180148,...,0.133868,0.132072,5110.000134,1.782739,3009.999990,1080.0,38.11,9384.672492,26.9000,9449.999809
2,1.368790e+11,3264.694290,3.475098,8.541906,4.467196,11.409329,0.002647,4.527132e+06,11.411977,0.000000,...,0.336716,0.328859,165539.993300,3.948290,94400.001530,12510.0,0.19,268.251917,11.2470,278029.998800
3,NaN,NaN,NaN,NaN,11.760709,NaN,NaN,0.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.49,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,2.440000,NaN,NaN,0.000000e+00,NaN,NaN,...,NaN,NaN,490.000009,6.532201,50.000001,0.0,18.58,4207.270740,0.3156,620.000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,NaN,NaN,NaN,NaN,9.356177,NaN,NaN,0.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.43,NaN,NaN,NaN
213,NaN,NaN,0.673616,10.605985,NaN,0.000000,0.000000,0.000000e+00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.73,177.716029,0.8120,NaN
214,2.051920e+10,666.413014,1.689545,4.257703,3.600000,0.645247,0.000000,0.000000e+00,0.699962,0.054714,...,NaN,NaN,9720.000267,0.315682,10619.999890,3080.0,3.60,68.202826,2.1000,23860.000610
215,2.043716e+10,1145.844603,1.170643,16.646641,3.563864,0.014706,4.445268,1.151537e+09,4.459974,0.000000,...,0.126504,0.123552,7730.000019,0.433396,15250.000000,13990.0,82.28,4496.550860,80.2000,37560.001370
216,1.535263e+10,1019.960476,2.699228,8.803571,1.910000,0.224736,2.501930,4.455984e+08,4.995018,2.268352,...,0.342751,0.334753,12380.000110,0.822472,12340.000150,5320.0,80.23,814.499743,12.2600,30829.999920

Imputation with Nuclear Norm Mininimization

In [13]:
!pip install fancyimpute

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fancyimpute
  Downloading fancyimpute-0.7.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting knnimpute>=0.1.0
  Downloading knnimpute-0.1.0.tar.gz (8.3 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.9/dist-packages (from fancyimpute) (1.2.2)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.9/dist-packages (from fancyimpute) (1.3.1)
Requirement already satisfied: cvxopt in /usr/local/lib/python3.9/dist-packages (from fancyimpute) (1.3.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.9/dist-packages (from fancyimpute) (7.2.2)
Collecting nose
  Downloading nose-1.3.7-py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 KB 5.2 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.16.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.9/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.22.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.1.1)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.9/dist-packages (from cvxpy->fancyimpute) (2.0.12)
Requirement already satisfied: osqp>=0.4.1 in /usr/local/lib/python3.9/dist-packages (from cvxpy->fancyimpute) (0.6.2.post0)
Requirement already satisfied: scs>=1.1.6 in /usr/local/lib/python3.9/dist-packages (from cvxpy->fancyimpute) (3.2.2)
Requirement already satisfied: setuptools>65.5.1 in /usr/local/lib/python3.9/dist-packages (from cvxpy->fancyimpute) (67.6.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.9/dist-packages (from pytest->fancyimpute) (1.0.0)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from pytest->fancyimpute) (2.0.1)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.9/dist-packages (from pytest->fancyimpute) (2.0.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.9/dist-packages (from pytest->fancyimpute) (22.2.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from pytest->fancyimpute) (23.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.9/dist-packages (from pytest->fancyimpute) (1.1.1)
Requirement already satisfied: qdldl in /usr/local/lib/python3.9/dist-packages (from osqp>=0.4.1->cvxpy->fancyimpute) (0.1.5.post3)
Building wheels for collected packages: fancyimpute, knnimpute
  Building wheel for fancyimpute (setup.py) ... done
  Created wheel for fancyimpute: filename=fancyimpute-0.7.0-py3-none-any.whl size=29898 sha256=eae33b551b82419550b0f2907aa787a113dcb504ed2f396f45d09a62bca292d3
  Stored in directory: /root/.cache/pip/wheels/f9/fc/6a/b0406b906bce293abe23c3b6da5a72637d2d04146ef1125a0b
  Building wheel for knnimpute (setup.py) ... done
  Created wheel for knnimpute: filename=knnimpute-0.1.0-py3-none-any.whl size=11352 sha256=76112cd99fdb88e8c9bc6f2c073ec9340ed97a1d4eee34ff6a51c0a58e06ac90
  Stored in directory: /root/.cache/pip/wheels/88/c4/be/e232c750d9bc360abf9a5e2cafe0d3e08e3605d2801bb11684
Successfully built fancyimpute knnimpute
Installing collected packages: nose, knnimpute, fancyimpute
Successfully installed fancyimpute-0.7.0 knnimpute-0.1.0 nose-1.3.7

In [14]:
from fancyimpute import NuclearNormMinimization

In [15]:
X_filled_nnm = NuclearNormMinimization().fit_transform(X)

===============================================================================
                                     CVXPY
                                     v1.3.1
===============================================================================
(CVXPY) Mar 25 04:17:17 PM: Your problem has 13237 variables, 1 constraints, and 0 parameters.
(CVXPY) Mar 25 04:17:17 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Mar 25 04:17:17 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Mar 25 04:17:17 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
(CVXPY) Mar 25 04:17:17 PM: Compiling problem (target solver=CVXOPT).
(CVXPY) Mar 25 04:17:17 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> CVXOPT
(CVXPY) Mar 25 04:17:17 PM: Applying reduction Dcp2Cone
(CVXPY) Mar 25 04:17:17 PM: Applying reduction CvxAttr2Constr
(CVXPY) Mar 25 04:17:18 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Mar 25 04:17:18 PM: Applying reduction CVXOPT
(CVXPY) Mar 25 04:17:18 PM: Finished problem compilation (took 1.030e+00 seconds).
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
(CVXPY) Mar 25 04:17:18 PM: Invoking solver CVXOPT  to obtain a solution.

OverflowError: ignored

ITERATIVE IMPUTAIOTN RANDOM FOREST ESTIMATOR

In [16]:
 from sklearn.ensemble import RandomForestRegressor

In [18]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [19]:
# Introduce IterativeImputer with an estimator
>>> imp = IterativeImputer(estimator=RandomForestRegressor())

In [20]:
# Fit to the dataset containing missing values
>>> imp.fit(X)

/usr/local/lib/python3.9/dist-packages/sklearn/impute/_iterative.py:785: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

IterativeImputer(estimator=RandomForestRegressor())

In [21]:
# Transform the dataset containing missing values
>>> X_filed = pd.DataFrame(imp.transform(X), columns = X.columns)

In [22]:
>>> X_filed = pd.DataFrame(imp.transform(X), columns = X.columns)

In [23]:
X_filed

,Adjusted net national income (current US$) [NY.ADJ.NNTY.CD],Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS],Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS],Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS],Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS],Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS],Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD],Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS],Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS],...,CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD],CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD],CO2 emissions (kt) [EN.ATM.CO2E.KT],CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC],Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE],Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE],Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],Renewable internal freshwater resources per capita (cubic meters) [ER.H2O.INTR.PC],"Renewable internal freshwater resources, total (billion cubic meters) [ER.H2O.INTR.K3]",Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]
0,1.681519e+10,458.344566,1.598055,7.417784,2.594447,0.154942,0.000000,0.000000e+00,0.397921,0.242979,...,0.080291,0.078417,6070.000172,0.165455,15909.999850,4690.0,17.96,1285.203958,47.150000,27690.000530
1,1.237962e+10,4318.911492,1.439030,17.030871,3.303909,0.991616,0.018862,2.855307e+06,1.190626,0.180148,...,0.133868,0.132072,5110.000134,1.782739,3009.999990,1080.0,38.11,9384.672492,26.900000,9449.999809
2,1.368790e+11,3264.694290,3.475098,8.541906,4.467196,11.409329,0.002647,4.527132e+06,11.411977,0.000000,...,0.336716,0.328859,165539.993300,3.948290,94400.001530,12510.0,0.19,268.251917,11.247000,278029.998800
3,1.067321e+09,9862.418544,1.972630,10.470673,11.760709,0.486320,0.000093,0.000000e+00,0.683543,0.440634,...,0.207998,0.203138,174855.301167,4.268198,80874.700065,9969.3,0.49,9259.463193,120.582702,265788.500928
4,3.912236e+09,37156.247479,0.687838,13.595767,2.440000,0.022602,0.000000,0.000000e+00,0.158647,0.071155,...,0.207652,0.203103,490.000009,6.532201,50.000001,0.0,18.58,4207.270740,0.315600,620.000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,3.514159e+09,29422.213299,1.915731,13.013706,9.356177,0.622321,0.000000,0.000000e+00,0.637307,0.074314,...,0.207831,0.203225,182344.201484,7.719888,56363.799946,10617.7,3.43,2342.835693,42.143560,257706.901498
213,1.675358e+10,3165.056280,0.673616,10.605985,5.743418,0.000000,0.000000,0.000000e+00,0.391340,0.238792,...,0.207365,0.203818,179023.900372,3.714701,81291.800503,21141.8,12.73,177.716029,0.812000,283953.200525
214,2.051920e+10,666.413014,1.689545,4.257703,3.600000,0.645247,0.000000,0.000000e+00,0.699962,0.054714,...,0.208075,0.203958,9720.000267,0.315682,10619.999890,3080.0,3.60,68.202826,2.100000,23860.000610
215,2.043716e+10,1145.844603,1.170643,16.646641,3.563864,0.014706,4.445268,1.151537e+09,4.459974,0.000000,...,0.126504,0.123552,7730.000019,0.433396,15250.000000,13990.0,82.28,4496.550860,80.200000,37560.001370
216,1.535263e+10,1019.960476,2.699228,8.803571,1.910000,0.224736,2.501930,4.455984e+08,4.995018,2.268352,...,0.342751,0.334753,12380.000110,0.822472,12340.000150,5320.0,80.23,814.499743,12.260000,30829.999920

In [24]:
X_filed.isna().sum()

Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]                               0
Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]                 0
Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS]                    0
Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS]             0
Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]                    0
                                                                                         ..
Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]      0
Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]       0
Renewable internal freshwater resources per capita (cubic meters) [ER.H2O.INTR.PC]        0
Renewable internal freshwater resources, total (billion cubic meters) [ER.H2O.INTR.K3]    0
Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]                 0
Length: 61, dtype: int64

In [25]:
X_filed.to_csv(r'C:\Users\isabe\OneDrive - Università degli Studi di Milano\second year\1st trimester\adv multivariate statistics\AMS\filled_data_colab.csv')

In [26]:
from google.colab import files

In [27]:
X_filed.to_csv('filled_colab.csv') 
files.download('filled_colab.csv')