In [1]:
import pandas as pd
import numpy as np

In [53]:
from pandas.api.types import CategoricalDtype

In [163]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [10]:
data = pd.read_excel("wdi2018.xlsx")

In [11]:
data

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%) [SG.VAW.REAS.ZS],Women who believe a husband is justified in beating his wife when she argues with him (%) [SG.VAW.ARGU.ZS],Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS],Women who believe a husband is justified in beating his wife when she goes out without telling him (%) [SG.VAW.GOES.ZS],Women who believe a husband is justified in beating his wife when she neglects the children (%) [SG.VAW.NEGL.ZS],Women who believe a husband is justified in beating his wife when she refuses sex with him (%) [SG.VAW.REFU.ZS],Women who were first married by age 15 (% of women ages 20-24) [SP.M15.2024.FE.ZS],Women who were first married by age 18 (% of women ages 20-24) [SP.M18.2024.FE.ZS],Women's share of population ages 15+ living with HIV (%) [SH.DYN.AIDS.FE.ZS],Young people (ages 15-24) newly infected with HIV [SH.HIV.INCD.YG]
0,2018,YR2018,Afghanistan,AFG,30.9,13.85,81.6,96.616135,95.586174,99.626022,...,..,..,..,..,..,..,..,..,29,500
1,2018,YR2018,Albania,ALB,79.8,62.5,92.2,100,100,100,...,6.8,1.8,0.8,3.7,5.2,0.9,1.4,11.8,25.9,100
2,2018,YR2018,Algeria,DZA,99.6,98.7,100,99.697838,99.071304,99.933952,...,..,..,..,..,..,..,..,..,46.5,500
3,2018,YR2018,American Samoa,ASM,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,2018,YR2018,Andorra,AND,100,100,100,100,100,100,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2018,YR2018,Sub-Saharan Africa,SSF,16.250483,5.54069,32.865363,46.267489,26.955024,73.688568,...,..,..,..,..,..,..,..,..,60.654807,..
262,2018,YR2018,Sub-Saharan Africa (excluding high income),SSA,16.243064,5.534628,32.856981,46.262729,26.948988,73.684042,...,..,..,..,..,..,..,..,..,60.654807,..
263,2018,YR2018,Sub-Saharan Africa (IDA & IBRD countries),TSS,16.250483,5.54069,32.865363,46.267489,26.955024,73.688568,...,..,..,..,..,..,..,..,..,60.654807,..
264,2018,YR2018,Upper middle income,UMC,81.734674,63.792109,91.377499,99.238818,98.74761,99.622869,...,..,..,..,..,..,..,..,..,..,..
265,2018,YR2018,World,WLD,67.051055,44.034131,85.610808,89.478902,83.108318,97.394112,...,..,..,..,..,..,..,..,..,53.6,480000

In [15]:
data = data.replace(to_replace='...', value=np.NaN)

In [16]:
data

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%) [SG.VAW.REAS.ZS],Women who believe a husband is justified in beating his wife when she argues with him (%) [SG.VAW.ARGU.ZS],Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS],Women who believe a husband is justified in beating his wife when she goes out without telling him (%) [SG.VAW.GOES.ZS],Women who believe a husband is justified in beating his wife when she neglects the children (%) [SG.VAW.NEGL.ZS],Women who believe a husband is justified in beating his wife when she refuses sex with him (%) [SG.VAW.REFU.ZS],Women who were first married by age 15 (% of women ages 20-24) [SP.M15.2024.FE.ZS],Women who were first married by age 18 (% of women ages 20-24) [SP.M18.2024.FE.ZS],Women's share of population ages 15+ living with HIV (%) [SH.DYN.AIDS.FE.ZS],Young people (ages 15-24) newly infected with HIV [SH.HIV.INCD.YG]
0,2018,YR2018,Afghanistan,AFG,30.900000,13.850000,81.600000,96.616135,95.586174,99.626022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,500.0
1,2018,YR2018,Albania,ALB,79.800000,62.500000,92.200000,100.000000,100.000000,100.000000,...,6.8,1.8,0.8,3.7,5.2,0.9,1.4,11.8,25.900000,100.0
2,2018,YR2018,Algeria,DZA,99.600000,98.700000,100.000000,99.697838,99.071304,99.933952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.500000,500.0
3,2018,YR2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,YR2018,Andorra,AND,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2018,YR2018,Sub-Saharan Africa,SSF,16.250483,5.540690,32.865363,46.267489,26.955024,73.688568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
262,2018,YR2018,Sub-Saharan Africa (excluding high income),SSA,16.243064,5.534628,32.856981,46.262729,26.948988,73.684042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
263,2018,YR2018,Sub-Saharan Africa (IDA & IBRD countries),TSS,16.250483,5.540690,32.865363,46.267489,26.955024,73.688568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.654807,NaN
264,2018,YR2018,Upper middle income,UMC,81.734674,63.792109,91.377499,99.238818,98.747610,99.622869,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,2018,YR2018,World,WLD,67.051055,44.034131,85.610808,89.478902,83.108318,97.394112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.600000,480000.0

In [17]:
#% of missing values per column 

#Because division of sum by length is mean, you can instead df_missing.sum()/len(df) use df_missing.mean()
result = data.isna().mean()

In [18]:
print(result)

Time                                                                                                               0.000000
Time Code                                                                                                          0.000000
Country Name                                                                                                       0.000000
Country Code                                                                                                       0.000000
Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]                              0.109023
                                                                                                                     ...
Women who believe a husband is justified in beating his wife when she refuses sex with him (%) [SG.VAW.REFU.ZS]    0.958647
Women who were first married by age 15 (% of women ages 20-24) [SP.M15.2024.FE.ZS]                                 0.890977
Women who were first married by age 18 (% of women ages 20-24) [SP.M18.2024.FE.ZS]                                 0.890977
Women's share of population ages 15+ living with HIV (%) [SH.DYN.AIDS.FE.ZS]                                       0.259398
Young people (ages 15-24) newly infected with HIV [SH.HIV.INCD.YG]                                                 0.503759
Length: 1446, dtype: float64

In [19]:
#remove columns with >20% NA
data_filtered80 = data.loc[:,result < .2]
#print(list(data_filtered80.columns))

print(len(list(data_filtered80.columns)))

448

In [23]:
income_group = pd.read_csv("income.csv")

In [24]:
income_group

    country code                country income
0            AFG            Afghanistan      L
1            ALB                Albania     UM
2            DZA                Algeria     UM
3            ASM         American Samoa     UM
4            AND                Andorra      H
..           ...                    ...    ...
213          VIR  Virgin Islands (U.S.)      H
214          PSE     West Bank and Gaza     LM
215          YEM            Yemen, Rep.      L
216          ZMB                 Zambia     LM
217          ZWE               Zimbabwe     LM

[218 rows x 3 columns]

In [37]:
income_group = income_group.rename(columns={"country code": "Country Code", "country": "Country Name", "income" : "Income Group"})

In [38]:
income_group.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Code  218 non-null    object
 1   Country Name  218 non-null    object
 2   Income Group  218 non-null    object
dtypes: object(3)
memory usage: 5.2+ KB

In [48]:
income_group = income_group.drop(['Country Name'], axis=1)

In [39]:
data_filtered80.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 448 columns):
 #    Column                                                                                                                                           Dtype
---   ------                                                                                                                                           -----
 0    Time                                                                                                                                             int64
 1    Time Code                                                                                                                                        object
 2    Country Name                                                                                                                                     object
 3    Country Code                                                                                                                                     object
 4    Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]                                                            float64
 5    Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]                                            float64
 6    Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]                                            float64
 7    Access to electricity (% of population) [EG.ELC.ACCS.ZS]                                                                                         float64
 8    Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]                                                                         float64
 9    Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]                                                                         float64
 10   Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]                                                                                      float64
 11   Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]                                                                        float64
 12   Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS]                                                                           float64
 13   Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS]                                                                    float64
 14   Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]                                                                           float64
 15   Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS]                                                                                float64
 16   Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS]                                                                               float64
 17   Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD]                                                                               float64
 18   Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS]                                                                     float64
 19   Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS]                                                                            float64
 20   Adjusted savings: particulate emission damage (% of GNI) [NY.ADJ.DPEM.GN.ZS]                                                                     float64
 21   Adolescent fertility rate (births per 1,000 women ages 15-19) [SP.ADO.TFRT]                                                                      float64
 22   Age dependency ratio (% of working-age population) [SP.POP.DPND]                                                                                 float64
 23   Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]                                                                         float64
 24   Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]                                                                       float64
 25   Agricultural land (% of land area) [AG.LND.AGRI.ZS]                                                                                              float64
 26   Agricultural land (sq. km) [AG.LND.AGRI.K2]                                                                                                      float64
 27   Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]                                                   float64
 28   Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]                                             float64
 29   Agriculture, forestry, and fishing, value added (% of GDP) [NV.AGR.TOTL.ZS]                                                                      float64
 30   Agriculture, forestry, and fishing, value added (annual % growth) [NV.AGR.TOTL.KD.ZG]                                                            float64
 31   Agriculture, forestry, and fishing, value added (constant 2015 US$) [NV.AGR.TOTL.KD]                                                             float64
 32   Agriculture, forestry, and fishing, value added (current US$) [NV.AGR.TOTL.CD]                                                                   float64
 33   Agriculture, forestry, and fishing, value added per worker (constant 2015 US$) [NV.AGR.EMPL.KD]                                                  float64
 34   Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal) [ER.H2O.FWAG.ZS]                                                   float64
 35   Annual freshwater withdrawals, domestic (% of total freshwater withdrawal) [ER.H2O.FWDM.ZS]                                                      float64
 36   Annual freshwater withdrawals, industry (% of total freshwater withdrawal) [ER.H2O.FWIN.ZS]                                                      float64
 37   Annual freshwater withdrawals, total (% of internal resources) [ER.H2O.FWTL.ZS]                                                                  float64
 38   Annual freshwater withdrawals, total (billion cubic meters) [ER.H2O.FWTL.K3]                                                                     float64
 39   Aquaculture production (metric tons) [ER.FSH.AQUA.MT]                                                                                            float64
 40   Arable land (% of land area) [AG.LND.ARBL.ZS]                                                                                                    float64
 41   Arable land (hectares per person) [AG.LND.ARBL.HA.PC]                                                                                            float64
 42   Armed forces personnel, total [MS.MIL.TOTL.P1]                                                                                                   float64
 43   Automated teller machines (ATMs) (per 100,000 adults) [FB.ATM.TOTL.P5]                                                                           float64
 44   Bird species, threatened [EN.BIR.THRD.NO]                                                                                                        float64
 45   Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]                                                                                            float64
 46   Business extent of disclosure index (0=less disclosure to 10=more disclosure) [IC.BUS.DISC.XQ]                                                   float64
 47   Capture fisheries production (metric tons) [ER.FSH.CAPT.MT]                                                                                      float64
 48   Cereal production (metric tons) [AG.PRD.CREL.MT]                                                                                                 float64
 49   Cereal yield (kg per hectare) [AG.YLD.CREL.KG]                                                                                                   float64
 50   Claims on central government, etc. (% GDP) [FS.AST.CGOV.GD.ZS]                                                                                   float64
 51   CO2 emissions (kg per 2015 US$ of GDP) [EN.ATM.CO2E.KD.GD]                                                                                       float64
 52   CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]                                                                                  float64
 53   CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD]                                                                                          float64
 54   CO2 emissions (kt) [EN.ATM.CO2E.KT]                                                                                                              float64
 55   CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]                                                                                          float64
 56   Coal rents (% of GDP) [NY.GDP.COAL.RT.ZS]                                                                                                        float64
 57   Commercial bank branches (per 100,000 adults) [FB.CBK.BRCH.P5]                                                                                   float64
 58   Commercial service exports (current US$) [TX.VAL.SERV.CD.WT]                                                                                     float64
 59   Commercial service imports (current US$) [TM.VAL.SERV.CD.WT]                                                                                     float64
 60   Communications, computer, etc. (% of service exports, BoP) [BX.GSR.CMCP.ZS]                                                                      float64
 61   Communications, computer, etc. (% of service imports, BoP) [BM.GSR.CMCP.ZS]                                                                      float64
 62   Compulsory education, duration (years) [SE.COM.DURS]                                                                                             float64
 63   Computer, communications and other services (% of commercial service exports) [TX.VAL.OTHR.ZS.WT]                                                float64
 64   Computer, communications and other services (% of commercial service imports) [TM.VAL.OTHR.ZS.WT]                                                float64
 65   Contributing family workers, female (% of female employment) (modeled ILO estimate) [SL.FAM.WORK.FE.ZS]                                          float64
 66   Contributing family workers, male (% of male employment) (modeled ILO estimate) [SL.FAM.WORK.MA.ZS]                                              float64
 67   Contributing family workers, total (% of total employment) (modeled ILO estimate) [SL.FAM.WORK.ZS]                                               float64
 68   Cost of business start-up procedures (% of GNI per capita) [IC.REG.COST.PC.ZS]                                                                   float64
 69   Cost of business start-up procedures, female (% of GNI per capita) [IC.REG.COST.PC.FE.ZS]                                                        float64
 70   Cost of business start-up procedures, male (% of GNI per capita) [IC.REG.COST.PC.MA.ZS]                                                          float64
 71   Cost to export, border compliance (US$) [IC.EXP.CSBC.CD]                                                                                         float64
 72   Cost to export, documentary compliance (US$) [IC.EXP.CSDC.CD]                                                                                    float64
 73   Cost to import, border compliance (US$) [IC.IMP.CSBC.CD]                                                                                         float64
 74   Cost to import, documentary compliance (US$) [IC.IMP.CSDC.CD]                                                                                    float64
 75   Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS]                                                                                        float64
 76   Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD]                                                                          float64
 77   Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]                                                         float64
 78   Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]                                                                                            float64
 79   DEC alternative conversion factor (LCU per US$) [PA.NUS.ATLS]                                                                                    float64
 80   Depth of credit information index (0=low to 8=high) [IC.CRD.INFO.XQ]                                                                             float64
 81   Domestic credit to private sector (% of GDP) [FS.AST.PRVT.GD.ZS]                                                                                 float64
 82   Domestic credit to private sector by banks (% of GDP) [FD.AST.PRVT.GD.ZS]                                                                        float64
 83   Domestic general government health expenditure (% of current health expenditure) [SH.XPD.GHED.CH.ZS]                                             float64
 84   Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS]                                                                    float64
 85   Domestic general government health expenditure per capita (current US$) [SH.XPD.GHED.PC.CD]                                                      float64
 86   Domestic general government health expenditure per capita, PPP (current international $) [SH.XPD.GHED.PP.CD]                                     float64
 87   Domestic private health expenditure (% of current health expenditure) [SH.XPD.PVTD.CH.ZS]                                                        float64
 88   Domestic private health expenditure per capita (current US$) [SH.XPD.PVTD.PC.CD]                                                                 float64
 89   Domestic private health expenditure per capita, PPP (current international $) [SH.XPD.PVTD.PP.CD]                                                float64
 90   Ease of doing business score (0 = lowest performance to 100 = best performance) [IC.BUS.DFRN.XQ]                                                 float64
 91   Employers, female (% of female employment) (modeled ILO estimate) [SL.EMP.MPYR.FE.ZS]                                                            float64
 92   Employers, male (% of male employment) (modeled ILO estimate) [SL.EMP.MPYR.MA.ZS]                                                                float64
 93   Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]                                                                 float64
 94   Employment in agriculture (% of total employment) (modeled ILO estimate) [SL.AGR.EMPL.ZS]                                                        float64
 95   Employment in agriculture, female (% of female employment) (modeled ILO estimate) [SL.AGR.EMPL.FE.ZS]                                            float64
 96   Employment in agriculture, male (% of male employment) (modeled ILO estimate) [SL.AGR.EMPL.MA.ZS]                                                float64
 97   Employment in industry (% of total employment) (modeled ILO estimate) [SL.IND.EMPL.ZS]                                                           float64
 98   Employment in industry, female (% of female employment) (modeled ILO estimate) [SL.IND.EMPL.FE.ZS]                                               float64
 99   Employment in industry, male (% of male employment) (modeled ILO estimate) [SL.IND.EMPL.MA.ZS]                                                   float64
 100  Employment in services (% of total employment) (modeled ILO estimate) [SL.SRV.EMPL.ZS]                                                           float64
 101  Employment in services, female (% of female employment) (modeled ILO estimate) [SL.SRV.EMPL.FE.ZS]                                               float64
 102  Employment in services, male (% of male employment) (modeled ILO estimate) [SL.SRV.EMPL.MA.ZS]                                                   float64
 103  Employment to population ratio, 15+, female (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.FE.ZS]                                                    float64
 104  Employment to population ratio, 15+, male (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.MA.ZS]                                                      float64
 105  Employment to population ratio, 15+, total (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.ZS]                                                        float64
 106  Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate) [SL.EMP.1524.SP.FE.ZS]                                             float64
 107  Employment to population ratio, ages 15-24, male (%) (modeled ILO estimate) [SL.EMP.1524.SP.MA.ZS]                                               float64
 108  Employment to population ratio, ages 15-24, total (%) (modeled ILO estimate) [SL.EMP.1524.SP.ZS]                                                 float64
 109  Exports of goods and services (% of GDP) [NE.EXP.GNFS.ZS]                                                                                        float64
 110  Exports of goods and services (BoP, current US$) [BX.GSR.GNFS.CD]                                                                                float64
 111  Exports of goods and services (current US$) [NE.EXP.GNFS.CD]                                                                                     float64
 112  Exports of goods, services and primary income (BoP, current US$) [BX.GSR.TOTL.CD]                                                                float64
 113  External balance on goods and services (% of GDP) [NE.RSB.GNFS.ZS]                                                                               float64
 114  External health expenditure (% of current health expenditure) [SH.XPD.EHEX.CH.ZS]                                                                float64
 115  External health expenditure per capita (current US$) [SH.XPD.EHEX.PC.CD]                                                                         float64
 116  External health expenditure per capita, PPP (current international $) [SH.XPD.EHEX.PP.CD]                                                        float64
 117  Fertility rate, total (births per woman) [SP.DYN.TFRT.IN]                                                                                        float64
 118  Final consumption expenditure (current US$) [NE.CON.TOTL.CD]                                                                                     float64
 119  Fish species, threatened [EN.FSH.THRD.NO]                                                                                                        float64
 120  Fixed broadband subscriptions [IT.NET.BBND]                                                                                                      float64
 121  Fixed broadband subscriptions (per 100 people) [IT.NET.BBND.P2]                                                                                  float64
 122  Fixed telephone subscriptions [IT.MLT.MAIN]                                                                                                      float64

In [40]:
full_data = data_filtered80

In [69]:
full_data_plus_income_group = pd.merge(full_data, income_group, on = "Country Code")

In [70]:
full_data_plus_income_group

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Urban population (% of total population) [SP.URB.TOTL.IN.ZS],Urban population growth (annual %) [SP.URB.GROW],"Vulnerable employment, female (% of female employment) (modeled ILO estimate) [SL.EMP.VULN.FE.ZS]","Vulnerable employment, male (% of male employment) (modeled ILO estimate) [SL.EMP.VULN.MA.ZS]","Vulnerable employment, total (% of total employment) (modeled ILO estimate) [SL.EMP.VULN.ZS]","Wage and salaried workers, female (% of female employment) (modeled ILO estimate) [SL.EMP.WORK.FE.ZS]","Wage and salaried workers, male (% of male employment) (modeled ILO estimate) [SL.EMP.WORK.MA.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]","Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal) [ER.GDP.FWTL.M3.KD]",Income Group
0,2018,YR2018,Afghanistan,AFG,30.9,13.85,81.6,96.616135,95.586174,99.626022,...,25.495,3.850833,89.920004,76.949996,79.619999,7.870000,20.200001,17.660000,1.047290,L
1,2018,YR2018,Albania,ALB,79.8,62.50,92.2,100.000000,100.000000,100.000000,...,60.319,1.317162,51.700001,52.540001,52.190001,47.020000,42.730000,44.520000,13.259350,UM
2,2018,YR2018,Algeria,DZA,99.6,98.70,100.0,99.697838,99.071304,99.933952,...,72.629,2.700947,23.400001,28.090001,27.349999,74.580002,66.790001,68.019997,17.914671,UM
3,2018,YR2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,87.153,-2.142604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UM
4,2018,YR2018,Andorra,AND,100.0,100.00,100.0,100.000000,100.000000,100.000000,...,88.062,1.480831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2018,YR2018,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,100.000000,100.000000,100.000000,...,95.721,-0.138546,3.220000,3.220000,3.220000,93.419998,93.410004,93.419998,NaN,H
213,2018,YR2018,West Bank and Gaza,PSE,NaN,NaN,NaN,100.000000,100.000000,100.000000,...,76.164,2.888119,22.110001,23.389999,23.180001,75.470001,68.680000,69.739998,52.106106,LM
214,2018,YR2018,"Yemen, Rep.",YEM,61.5,42.90,93.7,62.000000,NaN,NaN,...,36.642,4.209541,60.969999,46.660002,47.630000,38.029999,45.830002,45.299999,10.319535,L
215,2018,YR2018,Zambia,ZMB,11.9,2.10,24.6,40.317890,12.466436,76.461876,...,43.521,4.322060,84.240002,66.379998,74.879999,15.540000,33.340000,24.860001,15.106607,LM
216,2018,YR2018,Zimbabwe,ZWE,29.9,6.40,79.1,45.572647,26.617121,85.468765,...,32.209,1.933653,77.170002,56.380000,66.910002,22.559999,43.020000,32.650002,5.837433,LM

In [71]:
full_data_plus_income_group['Income Group'].unique()

array(['L', 'UM', 'H', 'LM'], dtype=object)

In [72]:
category_values = ['H', 'UM', 'LM', 'L']

category_order = CategoricalDtype(category_values, ordered=True)

full_data_plus_income_group.loc[:,'Income Group'] = full_data_plus_income_group.loc[:,'Income Group'].astype(category_order)

In [73]:
full_data_plus_income_group['Income Group'].unique()

['L', 'UM', 'H', 'LM']
Categories (4, object): ['H' < 'UM' < 'LM' < 'L']

In [74]:
full_data_plus_income_group

,Time,Time Code,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",...,Urban population (% of total population) [SP.URB.TOTL.IN.ZS],Urban population growth (annual %) [SP.URB.GROW],"Vulnerable employment, female (% of female employment) (modeled ILO estimate) [SL.EMP.VULN.FE.ZS]","Vulnerable employment, male (% of male employment) (modeled ILO estimate) [SL.EMP.VULN.MA.ZS]","Vulnerable employment, total (% of total employment) (modeled ILO estimate) [SL.EMP.VULN.ZS]","Wage and salaried workers, female (% of female employment) (modeled ILO estimate) [SL.EMP.WORK.FE.ZS]","Wage and salaried workers, male (% of male employment) (modeled ILO estimate) [SL.EMP.WORK.MA.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]","Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal) [ER.GDP.FWTL.M3.KD]",Income Group
0,2018,YR2018,Afghanistan,AFG,30.9,13.85,81.6,96.616135,95.586174,99.626022,...,25.495,3.850833,89.920004,76.949996,79.619999,7.870000,20.200001,17.660000,1.047290,L
1,2018,YR2018,Albania,ALB,79.8,62.50,92.2,100.000000,100.000000,100.000000,...,60.319,1.317162,51.700001,52.540001,52.190001,47.020000,42.730000,44.520000,13.259350,UM
2,2018,YR2018,Algeria,DZA,99.6,98.70,100.0,99.697838,99.071304,99.933952,...,72.629,2.700947,23.400001,28.090001,27.349999,74.580002,66.790001,68.019997,17.914671,UM
3,2018,YR2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,87.153,-2.142604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UM
4,2018,YR2018,Andorra,AND,100.0,100.00,100.0,100.000000,100.000000,100.000000,...,88.062,1.480831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2018,YR2018,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,100.000000,100.000000,100.000000,...,95.721,-0.138546,3.220000,3.220000,3.220000,93.419998,93.410004,93.419998,NaN,H
213,2018,YR2018,West Bank and Gaza,PSE,NaN,NaN,NaN,100.000000,100.000000,100.000000,...,76.164,2.888119,22.110001,23.389999,23.180001,75.470001,68.680000,69.739998,52.106106,LM
214,2018,YR2018,"Yemen, Rep.",YEM,61.5,42.90,93.7,62.000000,NaN,NaN,...,36.642,4.209541,60.969999,46.660002,47.630000,38.029999,45.830002,45.299999,10.319535,L
215,2018,YR2018,Zambia,ZMB,11.9,2.10,24.6,40.317890,12.466436,76.461876,...,43.521,4.322060,84.240002,66.379998,74.879999,15.540000,33.340000,24.860001,15.106607,LM
216,2018,YR2018,Zimbabwe,ZWE,29.9,6.40,79.1,45.572647,26.617121,85.468765,...,32.209,1.933653,77.170002,56.380000,66.910002,22.559999,43.020000,32.650002,5.837433,LM

In [75]:
full_data_plus_income_group = full_data_plus_income_group.drop(['Time Code'], axis=1)

In [76]:
full_data_plus_income_group

,Time,Country Name,Country Code,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Adjusted net national income (current US$) [NY.ADJ.NNTY.CD],...,Urban population (% of total population) [SP.URB.TOTL.IN.ZS],Urban population growth (annual %) [SP.URB.GROW],"Vulnerable employment, female (% of female employment) (modeled ILO estimate) [SL.EMP.VULN.FE.ZS]","Vulnerable employment, male (% of male employment) (modeled ILO estimate) [SL.EMP.VULN.MA.ZS]","Vulnerable employment, total (% of total employment) (modeled ILO estimate) [SL.EMP.VULN.ZS]","Wage and salaried workers, female (% of female employment) (modeled ILO estimate) [SL.EMP.WORK.FE.ZS]","Wage and salaried workers, male (% of male employment) (modeled ILO estimate) [SL.EMP.WORK.MA.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]","Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal) [ER.GDP.FWTL.M3.KD]",Income Group
0,2018,Afghanistan,AFG,30.9,13.85,81.6,96.616135,95.586174,99.626022,1.681519e+10,...,25.495,3.850833,89.920004,76.949996,79.619999,7.870000,20.200001,17.660000,1.047290,L
1,2018,Albania,ALB,79.8,62.50,92.2,100.000000,100.000000,100.000000,1.237962e+10,...,60.319,1.317162,51.700001,52.540001,52.190001,47.020000,42.730000,44.520000,13.259350,UM
2,2018,Algeria,DZA,99.6,98.70,100.0,99.697838,99.071304,99.933952,1.368789e+11,...,72.629,2.700947,23.400001,28.090001,27.349999,74.580002,66.790001,68.019997,17.914671,UM
3,2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.153,-2.142604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UM
4,2018,Andorra,AND,100.0,100.00,100.0,100.000000,100.000000,100.000000,NaN,...,88.062,1.480831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2018,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,...,95.721,-0.138546,3.220000,3.220000,3.220000,93.419998,93.410004,93.419998,NaN,H
213,2018,West Bank and Gaza,PSE,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,...,76.164,2.888119,22.110001,23.389999,23.180001,75.470001,68.680000,69.739998,52.106106,LM
214,2018,"Yemen, Rep.",YEM,61.5,42.90,93.7,62.000000,NaN,NaN,2.051920e+10,...,36.642,4.209541,60.969999,46.660002,47.630000,38.029999,45.830002,45.299999,10.319535,L
215,2018,Zambia,ZMB,11.9,2.10,24.6,40.317890,12.466436,76.461876,2.043716e+10,...,43.521,4.322060,84.240002,66.379998,74.879999,15.540000,33.340000,24.860001,15.106607,LM
216,2018,Zimbabwe,ZWE,29.9,6.40,79.1,45.572647,26.617121,85.468765,1.535263e+10,...,32.209,1.933653,77.170002,56.380000,66.910002,22.559999,43.020000,32.650002,5.837433,LM

In [94]:
column_list = list[full_data_plus_income_group.columns]

In [95]:
column_list

list[Index(['Time', 'Country Name', 'Country Code',
       'Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]',
       'Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]',
       'Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]',
       'Access to electricity (% of population) [EG.ELC.ACCS.ZS]',
       'Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]',
       'Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]',
       'Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]',
       ...
       'Urban population (% of total population) [SP.URB.TOTL.IN.ZS]',
       'Urban population growth (annual %) [SP.URB.GROW]',
       'Vulnerable employment, female (% of female employment) (modeled ILO estimate) [SL.EMP.VULN.FE.ZS]',
       'Vulnerable employment, male (% of male employment) (modeled ILO estimate) [SL.EMP.VULN.MA.ZS]',
       'Vulnerable employment, total (% of total employment) (modeled ILO estimate) [SL.EMP.VULN.ZS]',
       'Wage and salaried workers, female (% of female employment) (modeled ILO estimate) [SL.EMP.WORK.FE.ZS]',
       'Wage and salaried workers, male (% of male employment) (modeled ILO estimate) [SL.EMP.WORK.MA.ZS]',
       'Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]',
       'Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal) [ER.GDP.FWTL.M3.KD]',
       'Income Group'],
      dtype='object', length=448)]

In [100]:
'Energy intensity level of primary energy (MJ/$2017 PPP GDP)' in full_data_plus_income_group.columns

False

In [101]:
'CO2 intensity (kg per kg of oil equivalent energy use)' in full_data_plus_income_group.columns

False

In [82]:
retained_var_pol = [
    'Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]',
    'Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]',
    'Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]',
    'Access to electricity (% of population) [EG.ELC.ACCS.ZS]',
    'Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]',
    'Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]',
    'Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]',
    'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]',
    'Annual freshwater withdrawals, total (% of internal resources) [ER.H2O.FWTL.ZS]',
    'CO2 emissions (kg per 2015 US$ of GDP) [EN.ATM.CO2E.KD.GD]',
    'CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]',
    'CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD]',
    'CO2 emissions (kt) [EN.ATM.CO2E.KT]',
    'CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]',
    'Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]',
    'Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]',
    'Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]',
    'Renewable internal freshwater resources per capita (cubic meters) [ER.H2O.INTR.PC]',
    'Renewable internal freshwater resources, total (billion cubic meters) [ER.H2O.INTR.K3]',
    'Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]',    
]

retained_var_ec = [
    'Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]',
    'Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]',
    'Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS]',
    'Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS]',
    'Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]',
    'Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS]',
    'Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS]',
    'Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD]',
    'Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS]',
    'Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS]',
    'Adjusted savings: particulate emission damage (% of GNI) [NY.ADJ.DPEM.GN.ZS]',
    'Age dependency ratio (% of working-age population) [SP.POP.DPND]',
    'Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]',
    'Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]',
    'Contributing family workers, total (% of total employment) (modeled ILO estimate) [SL.FAM.WORK.ZS]',
    'Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]',
    'Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]',
    'Exports of goods and services (% of GDP) [NE.EXP.GNFS.ZS]',
    'Exports of goods and services (current US$) [NE.EXP.GNFS.CD]',
    'Final consumption expenditure (current US$) [NE.CON.TOTL.CD]',
    'GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
    'GDP (current US$) [NY.GDP.MKTP.CD]',
    'GDP per capita (current US$) [NY.GDP.PCAP.CD]',
    'GDP per person employed (constant 2017 PPP $) [SL.GDP.PCAP.EM.KD]', 
    'GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]',
    'General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]',
    'General government final consumption expenditure (current US$) [NE.CON.GOVT.CD]',
    'GNI (current US$) [NY.GNP.MKTP.CD]',
    'GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]',
    'Imports of goods and services (BoP, current US$) [BM.GSR.GNFS.CD]',
    'Imports of goods and services (current US$) [NE.IMP.GNFS.CD]',
    'Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]',
    'Industry (including construction), value added (annual % growth) [NV.IND.TOTL.KD.ZG]',
    'Industry (including construction), value added (current US$) [NV.IND.TOTL.CD]',
    'Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]',
    'Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]',
    'Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]',
    'Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]',
    'Manufacturing, value added (current US$) [NV.IND.MANF.CD]',
    'Population, total [SP.POP.TOTL]',
    'Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS]',
    'Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]',
    'Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]',
]

In [83]:
to_retain_vars = ['Country Code', 'Country Name'] + retained_var_pol + retained_var_ec + ['Income Group']

In [117]:
full_data_plus_income_group[to_retain_vars]

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE],Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE],...,"Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]","Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]","Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]","Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]","Manufacturing, value added (current US$) [NV.IND.MANF.CD]","Population, total [SP.POP.TOTL]",Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS],"Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group
0,AFG,Afghanistan,30.9,13.85,81.6,96.616135,95.586174,99.626022,10540.0,4310.0,...,0.626149,2.071349,6.160177,22.921060,1.134634e+09,36686784.0,71.4,11.110,17.660000,L
1,ALB,Albania,79.8,62.50,92.2,100.000000,100.000000,100.000000,2010.0,960.0,...,2.028060,1.473058,6.133262,6.259229,9.295837e+08,2866376.0,37.3,12.300,44.520000,UM
2,DZA,Algeria,99.6,98.70,100.0,99.697838,99.071304,99.933952,6820.0,5530.0,...,4.269990,6.757341,26.549953,-4.603222,4.643876e+10,41927007.0,66.1,10.416,68.019997,UM
3,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.695361,13.928013,16.867470,8.900000e+07,48424.0,NaN,NaN,NaN,UM
4,AND,Andorra,100.0,100.00,100.0,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,1.012478,3.610284,-2.170767,1.161904e+08,75013.0,NaN,NaN,NaN,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,1.441528,NaN,NaN,NaN,107001.0,NaN,12.245,93.419998,H
213,PSE,West Bank and Gaza,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,-0.195108,-0.301993,11.547252,0.341530,1.879500e+09,4569087.0,15.3,26.260,69.739998,LM
214,YEM,"Yemen, Rep.",61.5,42.90,93.7,62.000000,NaN,NaN,4360.0,2980.0,...,NaN,14.853665,NaN,NaN,NaN,30790513.0,26.6,13.076,45.299999,L
215,ZMB,Zambia,11.9,2.10,24.6,40.317890,12.466436,76.461876,10330.0,13510.0,...,7.494572,7.411571,6.847766,4.071350,1.801756e+09,17835893.0,15.6,5.030,24.860001,LM
216,ZWE,Zimbabwe,29.9,6.40,79.1,45.572647,26.617121,85.468765,6420.0,4660.0,...,10.618866,200.769578,13.678137,1.387913,4.671914e+09,15052184.0,31.6,6.784,32.650002,LM

In [118]:
data = full_data_plus_income_group[to_retain_vars]

In [119]:
data.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 217 entries, 0 to 216
Data columns (total 66 columns):
 #   Column                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                 --------------  -----
 0   Country Code                                                                                           217 non-null    object
 1   Country Name                                                                                           217 non-null    object
 2   Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]                  189 non-null    float64
 3   Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]  189 non-null    float64
 4   Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]  189 non-null    float64
 5   Access to electricity (% of population) [EG.ELC.ACCS.ZS]                                               215 non-null    float64
 6   Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]                               203 non-null    float64
 7   Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]                               207 non-null    float64
 8   Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]         187 non-null    float64
 9   Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]   187 non-null    float64
 10  Annual freshwater withdrawals, total (% of internal resources) [ER.H2O.FWTL.ZS]                        177 non-null    float64
 11  CO2 emissions (kg per 2015 US$ of GDP) [EN.ATM.CO2E.KD.GD]                                             186 non-null    float64
 12  CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]                                        182 non-null    float64
 13  CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD]                                                182 non-null    float64
 14  CO2 emissions (kt) [EN.ATM.CO2E.KT]                                                                    191 non-null    float64
 15  CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]                                                191 non-null    float64
 16  Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]                                           191 non-null    float64
 17  Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]                   190 non-null    float64
 18  Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]                    213 non-null    float64
 19  Renewable internal freshwater resources per capita (cubic meters) [ER.H2O.INTR.PC]                     183 non-null    float64
 20  Renewable internal freshwater resources, total (billion cubic meters) [ER.H2O.INTR.K3]                 183 non-null    float64
 21  Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]                              191 non-null    float64
 22  Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]                                            179 non-null    float64
 23  Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]                              179 non-null    float64
 24  Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS]                                 191 non-null    float64
 25  Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS]                          196 non-null    float64
 26  Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]                                 198 non-null    float64
 27  Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS]                                      194 non-null    float64
 28  Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS]                                     199 non-null    float64
 29  Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD]                                     217 non-null    float64
 30  Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS]                           179 non-null    float64
 31  Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS]                                  180 non-null    float64
 32  Adjusted savings: particulate emission damage (% of GNI) [NY.ADJ.DPEM.GN.ZS]                           175 non-null    float64
 33  Age dependency ratio (% of working-age population) [SP.POP.DPND]                                       217 non-null    float64
 34  Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]                               217 non-null    float64
 35  Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]                             217 non-null    float64
 36  Contributing family workers, total (% of total employment) (modeled ILO estimate) [SL.FAM.WORK.ZS]     187 non-null    float64
 37  Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]               187 non-null    float64
 38  Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]                       187 non-null    float64
 39  Exports of goods and services (% of GDP) [NE.EXP.GNFS.ZS]                                              186 non-null    float64
 40  Exports of goods and services (current US$) [NE.EXP.GNFS.CD]                                           186 non-null    float64
 41  Final consumption expenditure (current US$) [NE.CON.TOTL.CD]                                           178 non-null    float64
 42  GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]                                                              206 non-null    float64
 43  GDP (current US$) [NY.GDP.MKTP.CD]                                                                     209 non-null    float64
 44  GDP per capita (current US$) [NY.GDP.PCAP.CD]                                                          209 non-null    float64
 45  GDP per person employed (constant 2017 PPP $) [SL.GDP.PCAP.EM.KD]                                      175 non-null    float64
 46  GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]                                           194 non-null    float64
 47  General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]                           177 non-null    float64
 48  General government final consumption expenditure (current US$) [NE.CON.GOVT.CD]                        177 non-null    float64
 49  GNI (current US$) [NY.GNP.MKTP.CD]                                                                     200 non-null    float64
 50  GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]                                                 194 non-null    float64
 51  Imports of goods and services (BoP, current US$) [BM.GSR.GNFS.CD]                                      182 non-null    float64
 52  Imports of goods and services (current US$) [NE.IMP.GNFS.CD]                                           186 non-null    float64
 53  Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]                             199 non-null    float64
 54  Industry (including construction), value added (annual % growth) [NV.IND.TOTL.KD.ZG]                   190 non-null    float64
 55  Industry (including construction), value added (current US$) [NV.IND.TOTL.CD]                          199 non-null    float64
 56  Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]                                                 178 non-null    float64
 57  Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]                                                 206 non-null    float64
 58  Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]                                                 191 non-null    float64
 59  Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]                                       183 non-null    float64
 60  Manufacturing, value added (current US$) [NV.IND.MANF.CD]                                              191 non-null    float64
 61  Population, total [SP.POP.TOTL]                                                                        217 non-null    float64
 62  Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS]                                      189 non-null    float64
 63  Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]                   187 non-null    float64
 64  Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]       187 non-null    float64
 65  Income Group                                                                                           217 non-null    category
dtypes: category(1), float64(63), object(2)
memory usage: 112.3+ KB

In [102]:
energy_intensity = pd.read_excel("energy_intensity.xlsx")

In [104]:
carbon_intensity = pd.read_csv("carbon-intensity-electricity.csv")

In [105]:
energy_intensity

,Time,Time Code,Country Name,Country Code,Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]
0,2018,YR2018,Afghanistan,AFG,2.44
1,2018,YR2018,Albania,ALB,2.57
2,2018,YR2018,Algeria,DZA,5.19
3,2018,YR2018,American Samoa,ASM,..
4,2018,YR2018,Andorra,AND,..
...,...,...,...,...,...
266,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN
269,Data from database: World Development Indicators,NaN,NaN,NaN,NaN
270,Last Updated: 03/01/2023,NaN,NaN,NaN,NaN

In [107]:
energy_intensity.isna().mean()

Time                                                                               0.01107
Time Code                                                                          0.01845
Country Name                                                                       0.01845
Country Code                                                                       0.01845
Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]    0.01845
dtype: float64

In [122]:
energy_intensity = energy_intensity.drop(['Country Name', 'Time', 'Time Code'], axis=1)

In [123]:
energy_intensity_added = pd.merge(data, energy_intensity, on = "Country Code")

In [124]:
energy_intensity_added

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE],Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE],...,"Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]","Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]","Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]","Manufacturing, value added (current US$) [NV.IND.MANF.CD]","Population, total [SP.POP.TOTL]",Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS],"Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group,Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]
0,AFG,Afghanistan,30.9,13.85,81.6,96.616135,95.586174,99.626022,10540.0,4310.0,...,2.071349,6.160177,22.921060,1.134634e+09,36686784.0,71.4,11.110,17.660000,L,2.44
1,ALB,Albania,79.8,62.50,92.2,100.000000,100.000000,100.000000,2010.0,960.0,...,1.473058,6.133262,6.259229,9.295837e+08,2866376.0,37.3,12.300,44.520000,UM,2.57
2,DZA,Algeria,99.6,98.70,100.0,99.697838,99.071304,99.933952,6820.0,5530.0,...,6.757341,26.549953,-4.603222,4.643876e+10,41927007.0,66.1,10.416,68.019997,UM,5.19
3,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.695361,13.928013,16.867470,8.900000e+07,48424.0,NaN,NaN,NaN,UM,..
4,AND,Andorra,100.0,100.00,100.0,100.000000,100.000000,100.000000,NaN,NaN,...,1.012478,3.610284,-2.170767,1.161904e+08,75013.0,NaN,NaN,NaN,H,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,1.441528,NaN,NaN,NaN,107001.0,NaN,12.245,93.419998,H,..
213,PSE,West Bank and Gaza,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,-0.301993,11.547252,0.341530,1.879500e+09,4569087.0,15.3,26.260,69.739998,LM,2.55
214,YEM,"Yemen, Rep.",61.5,42.90,93.7,62.000000,NaN,NaN,4360.0,2980.0,...,14.853665,NaN,NaN,NaN,30790513.0,26.6,13.076,45.299999,L,..
215,ZMB,Zambia,11.9,2.10,24.6,40.317890,12.466436,76.461876,10330.0,13510.0,...,7.411571,6.847766,4.071350,1.801756e+09,17835893.0,15.6,5.030,24.860001,LM,7.35
216,ZWE,Zimbabwe,29.9,6.40,79.1,45.572647,26.617121,85.468765,6420.0,4660.0,...,200.769578,13.678137,1.387913,4.671914e+09,15052184.0,31.6,6.784,32.650002,LM,9.83

In [125]:
carbon_intensity

           Entity Code  Year  Carbon intensity of electricity (gCO2/kWh)
0     Afghanistan  AFG  2000                                  255.319140
1     Afghanistan  AFG  2001                                  118.644066
2     Afghanistan  AFG  2002                                  144.927540
3     Afghanistan  AFG  2003                                  255.319140
4     Afghanistan  AFG  2004                                  269.662900
...           ...  ...   ...                                         ...
5074     Zimbabwe  ZWE  2017                                  363.265320
5075     Zimbabwe  ZWE  2018                                  355.821560
5076     Zimbabwe  ZWE  2019                                  387.135930
5077     Zimbabwe  ZWE  2020                                  389.473700
5078     Zimbabwe  ZWE  2021                                  393.034850

[5079 rows x 4 columns]

In [126]:
carbon_intensity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5079 entries, 0 to 5078
Data columns (total 4 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Entity                                      5079 non-null   object
 1   Code                                        4615 non-null   object
 2   Year                                        5079 non-null   int64
 3   Carbon intensity of electricity (gCO2/kWh)  5079 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 158.8+ KB

In [127]:
carbon_intensity_2018 = carbon_intensity[carbon_intensity['Year'] == 2018]

In [128]:
carbon_intensity_2018

,Entity,Code,Year,Carbon intensity of electricity (gCO2/kWh)
18,Afghanistan,AFG,2018,136.752140
40,Africa,NaN,2018,505.281620
62,Africa (Ember),NaN,2018,505.416530
84,Albania,ALB,2018,24.561401
105,Algeria,DZA,2018,488.975200
...,...,...,...,...
4977,Vietnam,VNM,2018,432.812300
5009,World,OWID_WRL,2018,459.112820
5031,Yemen,YEM,2018,542.424260
5053,Zambia,ZMB,2018,130.192200
5075,Zimbabwe,ZWE,2018,355.821560

In [129]:
carbon_intensity_2018 = carbon_intensity_2018.drop(['Entity', 'Year'], axis=1)

In [130]:
carbon_intensity_2018

          Code  Carbon intensity of electricity (gCO2/kWh)
18         AFG                                  136.752140
40         NaN                                  505.281620
62         NaN                                  505.416530
84         ALB                                   24.561401
105        DZA                                  488.975200
...        ...                                         ...
4977       VNM                                  432.812300
5009  OWID_WRL                                  459.112820
5031       YEM                                  542.424260
5053       ZMB                                  130.192200
5075       ZWE                                  355.821560

[228 rows x 2 columns]

In [136]:
carbon_intensity_2018 = carbon_intensity_2018.rename(columns={"Code": "Country Code"})

In [137]:
carbon_intensity_2018

     Country Code  Carbon intensity of electricity (gCO2/kWh)
18            AFG                                  136.752140
40            NaN                                  505.281620
62            NaN                                  505.416530
84            ALB                                   24.561401
105           DZA                                  488.975200
...           ...                                         ...
4977          VNM                                  432.812300
5009     OWID_WRL                                  459.112820
5031          YEM                                  542.424260
5053          ZMB                                  130.192200
5075          ZWE                                  355.821560

[228 rows x 2 columns]

In [138]:
carbon_intensity_added = pd.merge(energy_intensity_added, carbon_intensity_2018, on = "Country Code")

In [139]:
carbon_intensity_added

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE],Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE],...,"Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]","Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]","Manufacturing, value added (current US$) [NV.IND.MANF.CD]","Population, total [SP.POP.TOTL]",Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS],"Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group,Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD],Carbon intensity of electricity (gCO2/kWh)
0,AFG,Afghanistan,30.9,13.85,81.6,96.616135,95.586174,99.626022,10540.0,4310.0,...,6.160177,22.921060,1.134634e+09,36686784.0,71.4,11.110,17.660000,L,2.44,136.752140
1,ALB,Albania,79.8,62.50,92.2,100.000000,100.000000,100.000000,2010.0,960.0,...,6.133262,6.259229,9.295837e+08,2866376.0,37.3,12.300,44.520000,UM,2.57,24.561401
2,DZA,Algeria,99.6,98.70,100.0,99.697838,99.071304,99.933952,6820.0,5530.0,...,26.549953,-4.603222,4.643876e+10,41927007.0,66.1,10.416,68.019997,UM,5.19,488.975200
3,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.928013,16.867470,8.900000e+07,48424.0,NaN,NaN,NaN,UM,..,687.500000
4,AGO,Angola,49.1,8.10,77.7,45.290001,7.333445,65.269997,16220.0,16140.0,...,6.059469,0.571521,4.713840e+09,31273533.0,49.1,9.522,21.620001,LM,2.95,137.850460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,NaN,NaN,107001.0,NaN,12.245,93.419998,H,..,688.524540
196,PSE,West Bank and Gaza,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,11.547252,0.341530,1.879500e+09,4569087.0,15.3,26.260,69.739998,LM,2.55,524.999940
197,YEM,"Yemen, Rep.",61.5,42.90,93.7,62.000000,NaN,NaN,4360.0,2980.0,...,NaN,NaN,NaN,30790513.0,26.6,13.076,45.299999,L,..,542.424260
198,ZMB,Zambia,11.9,2.10,24.6,40.317890,12.466436,76.461876,10330.0,13510.0,...,6.847766,4.071350,1.801756e+09,17835893.0,15.6,5.030,24.860001,LM,7.35,130.192200
199,ZWE,Zimbabwe,29.9,6.40,79.1,45.572647,26.617121,85.468765,6420.0,4660.0,...,13.678137,1.387913,4.671914e+09,15052184.0,31.6,6.784,32.650002,LM,9.83,355.821560

In [143]:
for e in carbon_intensity_added['Country Name']:
    print(e)

Afghanistan
Albania
Algeria
American Samoa
Angola
Antigua and Barbuda
Argentina
Armenia
Aruba
Australia
Austria
Azerbaijan
Bahamas, The
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
British Virgin Islands
Brunei Darussalam
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Cayman Islands
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo, Dem. Rep.
Congo, Rep.
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt, Arab Rep.
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Faroe Islands
Fiji
Finland
France
French Polynesia
Gabon
Gambia, The
Georgia
Germany
Ghana
Greece
Greenland
Grenada
Guam
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hong Kong SAR, China
Hungary
Iceland
India
Indonesia
Iran, Islamic Rep.
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, Dem. People's Rep.
Korea, Rep.
Kuwait
Kyrgyz Republic
Lao PDR
Latvia
Lebanon
Lesotho
Liberia
Libya
Lithuania
Luxembourg
Macao SAR, China
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Mauritania
Mauritius
Mexico
Moldova
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
Netherlands
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Puerto Rico
Qatar
Romania
Russian Federation
Rwanda
Samoa
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovak Republic
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
St. Kitts and Nevis
St. Lucia
St. Vincent and the Grenadines
Sudan
Suriname
Sweden
Switzerland
Syrian Arab Republic
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkiye
Turkmenistan
Turks and Caicos Islands
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Venezuela, RB
Vietnam
Virgin Islands (U.S.)
West Bank and Gaza
Yemen, Rep.
Zambia
Zimbabwe

In [150]:
list_col = carbon_intensity_added.columns

In [153]:
print(list_col)

Index(['Country Code', 'Country Name',
       'Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]',
       'Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]',
       'Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]',
       'Access to electricity (% of population) [EG.ELC.ACCS.ZS]',
       'Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]',
       'Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]',
       'Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]',
       'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]',
       'Annual freshwater withdrawals, total (% of internal resources) [ER.H2O.FWTL.ZS]',
       'CO2 emissions (kg per 2015 US$ of GDP) [EN.ATM.CO2E.KD.GD]',
       'CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]',
       'CO2 emissions (kg per PPP $ of GDP) [EN.ATM.CO2E.PP.GD]',
       'CO2 emissions (kt) [EN.ATM.CO2E.KT]',
       'CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]',
       'Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]',
       'Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]',
       'Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]',
       'Renewable internal freshwater resources per capita (cubic meters) [ER.H2O.INTR.PC]',
       'Renewable internal freshwater resources, total (billion cubic meters) [ER.H2O.INTR.K3]',
       'Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]',
       'Adjusted net national income (current US$) [NY.ADJ.NNTY.CD]',
       'Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]',
       'Adjusted savings: carbon dioxide damage (% of GNI) [NY.ADJ.DCO2.GN.ZS]',
       'Adjusted savings: consumption of fixed capital (% of GNI) [NY.ADJ.DKAP.GN.ZS]',
       'Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]',
       'Adjusted savings: energy depletion (% of GNI) [NY.ADJ.DNGY.GN.ZS]',
       'Adjusted savings: mineral depletion (% of GNI) [NY.ADJ.DMIN.GN.ZS]',
       'Adjusted savings: mineral depletion (current US$) [NY.ADJ.DMIN.CD]',
       'Adjusted savings: natural resources depletion (% of GNI) [NY.ADJ.DRES.GN.ZS]',
       'Adjusted savings: net forest depletion (% of GNI) [NY.ADJ.DFOR.GN.ZS]',
       'Adjusted savings: particulate emission damage (% of GNI) [NY.ADJ.DPEM.GN.ZS]',
       'Age dependency ratio (% of working-age population) [SP.POP.DPND]',
       'Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]',
       'Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]',
       'Contributing family workers, total (% of total employment) (modeled ILO estimate) [SL.FAM.WORK.ZS]',
       'Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]',
       'Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]',
       'Exports of goods and services (% of GDP) [NE.EXP.GNFS.ZS]',
       'Exports of goods and services (current US$) [NE.EXP.GNFS.CD]',
       'Final consumption expenditure (current US$) [NE.CON.TOTL.CD]',
       'GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
       'GDP (current US$) [NY.GDP.MKTP.CD]',
       'GDP per capita (current US$) [NY.GDP.PCAP.CD]',
       'GDP per person employed (constant 2017 PPP $) [SL.GDP.PCAP.EM.KD]',
       'GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]',
       'General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]',
       'General government final consumption expenditure (current US$) [NE.CON.GOVT.CD]',
       'GNI (current US$) [NY.GNP.MKTP.CD]',
       'GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]',
       'Imports of goods and services (BoP, current US$) [BM.GSR.GNFS.CD]',
       'Imports of goods and services (current US$) [NE.IMP.GNFS.CD]',
       'Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]',
       'Industry (including construction), value added (annual % growth) [NV.IND.TOTL.KD.ZG]',
       'Industry (including construction), value added (current US$) [NV.IND.TOTL.CD]',
       'Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]',
       'Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]',
       'Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]',
       'Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]',
       'Manufacturing, value added (current US$) [NV.IND.MANF.CD]',
       'Population, total [SP.POP.TOTL]',
       'Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS]',
       'Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]',
       'Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]',
       'Income Group',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]',
       'Carbon intensity of electricity (gCO2/kWh)'],
      dtype='object')

In [152]:
print(len(list_col))

68

In [154]:
carbon_intensity_added

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE],Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE],...,"Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]","Manufacturing, value added (annual % growth) [NV.IND.MANF.KD.ZG]","Manufacturing, value added (current US$) [NV.IND.MANF.CD]","Population, total [SP.POP.TOTL]",Total tax and contribution rate (% of profit) [IC.TAX.TOTL.CP.ZS],"Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group,Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD],Carbon intensity of electricity (gCO2/kWh)
0,AFG,Afghanistan,30.9,13.85,81.6,96.616135,95.586174,99.626022,10540.0,4310.0,...,6.160177,22.921060,1.134634e+09,36686784.0,71.4,11.110,17.660000,L,2.44,136.752140
1,ALB,Albania,79.8,62.50,92.2,100.000000,100.000000,100.000000,2010.0,960.0,...,6.133262,6.259229,9.295837e+08,2866376.0,37.3,12.300,44.520000,UM,2.57,24.561401
2,DZA,Algeria,99.6,98.70,100.0,99.697838,99.071304,99.933952,6820.0,5530.0,...,26.549953,-4.603222,4.643876e+10,41927007.0,66.1,10.416,68.019997,UM,5.19,488.975200
3,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.928013,16.867470,8.900000e+07,48424.0,NaN,NaN,NaN,UM,..,687.500000
4,AGO,Angola,49.1,8.10,77.7,45.290001,7.333445,65.269997,16220.0,16140.0,...,6.059469,0.571521,4.713840e+09,31273533.0,49.1,9.522,21.620001,LM,2.95,137.850460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,NaN,NaN,NaN,107001.0,NaN,12.245,93.419998,H,..,688.524540
196,PSE,West Bank and Gaza,NaN,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,...,11.547252,0.341530,1.879500e+09,4569087.0,15.3,26.260,69.739998,LM,2.55,524.999940
197,YEM,"Yemen, Rep.",61.5,42.90,93.7,62.000000,NaN,NaN,4360.0,2980.0,...,NaN,NaN,NaN,30790513.0,26.6,13.076,45.299999,L,..,542.424260
198,ZMB,Zambia,11.9,2.10,24.6,40.317890,12.466436,76.461876,10330.0,13510.0,...,6.847766,4.071350,1.801756e+09,17835893.0,15.6,5.030,24.860001,LM,7.35,130.192200
199,ZWE,Zimbabwe,29.9,6.40,79.1,45.572647,26.617121,85.468765,6420.0,4660.0,...,13.678137,1.387913,4.671914e+09,15052184.0,31.6,6.784,32.650002,LM,9.83,355.821560

In [155]:
variables = [
    'Country Code', 
    'Country Name',

#pollution variables
    'Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]',
    'Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]',
    'Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]',

    'Access to electricity (% of population) [EG.ELC.ACCS.ZS]',
    'Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]',
    'Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]',

    'Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]',

    'Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]',

    'CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]',

    'Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]',
    'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]',

    'Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]',
    'Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]',

    'Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]',
    'Carbon intensity of electricity (gCO2/kWh)',


#economics variables
    'Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]',
    'Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]',
    'Exports of goods and services (current US$) [NE.EXP.GNFS.CD]',
    'Imports of goods and services (current US$) [NE.IMP.GNFS.CD]',
    'Final consumption expenditure (current US$) [NE.CON.TOTL.CD]',
    'GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]',
    'GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
    'GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]',
    'Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]',
    'Population, total [SP.POP.TOTL]',
    'Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]',

    'Income Group'

]

In [166]:
num_variables = [

#pollution variables
    'Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]',
    'Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]',
    'Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]',

    'Access to electricity (% of population) [EG.ELC.ACCS.ZS]',
    'Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]',
    'Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]',

    'Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]',

    'Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]',

    'CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]',

    'Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]',
    'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]',

    'Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]',
    'Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]',

    'Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]',
    'Carbon intensity of electricity (gCO2/kWh)',


#economics variables
    'Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]',
    'Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]',
    'Exports of goods and services (current US$) [NE.EXP.GNFS.CD]',
    'Imports of goods and services (current US$) [NE.IMP.GNFS.CD]',
    'Final consumption expenditure (current US$) [NE.CON.TOTL.CD]',
    'GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]',
    'GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
    'GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]',
    'Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]',
    'Population, total [SP.POP.TOTL]',
    'Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]'

]

In [156]:
carbon_intensity_added[variables]

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE],...,Exports of goods and services (current US$) [NE.EXP.GNFS.CD],Imports of goods and services (current US$) [NE.IMP.GNFS.CD],Final consumption expenditure (current US$) [NE.CON.TOTL.CD],"GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]",GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],"GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]","Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]","Population, total [SP.POP.TOTL]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group
0,AFG,Afghanistan,30.9,13.85,81.6,96.616135,95.586174,99.626022,17.96,27690.000534,...,NaN,NaN,NaN,7.560042e+10,1.189228,7.821093e+10,13.387247,36686784.0,17.660000,L
1,ALB,Albania,79.8,62.50,92.2,100.000000,100.000000,100.000000,38.11,9449.999809,...,4.785178e+09,6.856193e+09,1.370054e+10,3.817186e+10,4.019360,3.864383e+10,21.279306,2866376.0,44.520000,UM
2,DZA,Algeria,99.6,98.70,100.0,99.697838,99.071304,99.933952,0.19,278029.998779,...,4.523397e+10,5.632890e+10,1.036736e+11,4.916310e+11,1.200000,4.907023e+11,38.805186,41927007.0,68.019997,UM
3,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,0.49,NaN,...,4.360000e+08,6.620000e+08,NaN,NaN,2.671119,NaN,NaN,48424.0,NaN,UM
4,AGO,Angola,49.1,8.10,77.7,45.290001,7.333445,65.269997,57.36,75239.997864,...,3.176775e+10,1.986966e+10,5.199370e+10,2.151179e+11,-1.316312,2.032423e+11,47.931542,31273533.0,21.620001,LM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,100.000000,100.000000,100.000000,3.43,NaN,...,2.084000e+09,4.163000e+09,4.352000e+09,NaN,1.904762,NaN,NaN,107001.0,93.419998,H
196,PSE,West Bank and Gaza,NaN,NaN,NaN,100.000000,100.000000,100.000000,12.73,NaN,...,2.598000e+09,9.023700e+09,1.804750e+10,2.886845e+10,1.227077,3.461983e+10,19.284126,4569087.0,69.739998,LM
197,YEM,"Yemen, Rep.",61.5,42.90,93.7,62.000000,NaN,NaN,3.60,23860.000610,...,1.308592e+09,9.344000e+09,NaN,NaN,0.752448,NaN,15.209188,30790513.0,45.299999,L
198,ZMB,Zambia,11.9,2.10,24.6,40.317890,12.466436,76.461876,82.28,37560.001373,...,9.987197e+09,9.717124e+09,1.517567e+10,6.110486e+10,4.034494,6.159734e+10,34.485322,17835893.0,24.860001,LM
199,ZWE,Zimbabwe,29.9,6.40,79.1,45.572647,26.617121,85.468765,80.23,30829.999924,...,8.936585e+09,9.695644e+09,3.008262e+10,3.611955e+10,5.009867,3.621026e+10,31.037898,15052184.0,32.650002,LM

In [157]:
data_reduced = carbon_intensity_added[variables]

In [173]:
data_reduced = data_reduced.replace(to_replace='..', value=np.NaN)

In [176]:
data_reduced_numerical = data_reduced[num_variables]

In [177]:
for e in data_reduced_numerical['Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]']:
    print(e)

2.44
2.57
5.19
nan
2.95
3.57
3.31
3.51
3.07
4.39
2.81
4.32
2.72
8.27
2.3
3.87
6.29
3.82
5.69
6.05
8.22
3.99
6.54
2.76
3.93
nan
5.85
4.98
4.6
7.71
2.68
4.61
4.43
7.1
1.9
8.56
3.85
3.49
6.39
2.29
3.12
13.82
6.12
1.98
3.48
3.13
1.37
2.74
4.28
2.14
2.02
2.94
2.06
3.1
3.59
3.27
3.72
nan
5.54
4.5
7.88
nan
2.12
5.37
3.4
nan
6.64
3.08
3.82
2.87
2.92
3.0
nan
2.54
nan
4.25
5.51
8.93
3.86
5.78
4.58
1.31
3.66
12.78
4.4
3.19
10.39
5.67
1.41
2.65
2.48
4.28
3.45
3.82
6.65
5.26
6.03
nan
5.46
7.07
5.88
4.7
3.35
3.36
8.08
13.59
7.16
3.22
2.37
0.47
8.5
3.28
4.5
2.56
4.76
1.36
3.35
2.15
3.09
5.09
6.37
3.42
3.18
12.07
3.52
3.44
5.15
5.68
3.17
nan
3.93
4.46
5.03
6.16
3.23
3.66
7.79
4.48
1.39
5.31
3.4
2.56
2.81
3.68
2.63
0.55
6.46
2.52
8.25
4.01
4.23
3.49
5.58
3.48
5.28
3.16
5.51
2.51
4.28
3.67
4.28
11.69
7.73
nan
2.77
1.76
2.59
2.86
2.67
4.47
3.57
3.97
1.66
11.72
4.73
6.49
4.5
2.12
8.48
2.87
19.34
3.85
2.59
13.33
4.92
10.17
7.51
4.11
2.41
4.61
2.79
9.05
3.8
nan
4.74
nan
2.55
nan
7.35
9.83

In [179]:
#MISSING VALUES IMPUTATION
# Introduce IterativeImputer with an estimator
imp = IterativeImputer(estimator=RandomForestRegressor())

In [180]:
# Fit to the dataset containing missing values
imp.fit(data_reduced_numerical)

C:\Users\isabe\anaconda3\lib\site-packages\sklearn\impute\_iterative.py:699: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

IterativeImputer(estimator=RandomForestRegressor())

In [181]:
# Transform the dataset containing missing values
filled = pd.DataFrame(imp.transform(data_reduced_numerical), columns = data_reduced_numerical.columns)

In [182]:
filled

,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE],CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD],Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE],...,"Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]",Exports of goods and services (current US$) [NE.EXP.GNFS.CD],Imports of goods and services (current US$) [NE.IMP.GNFS.CD],Final consumption expenditure (current US$) [NE.CON.TOTL.CD],"GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]",GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],"GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]","Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]","Population, total [SP.POP.TOTL]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]"
0,30.900,13.8500,81.600,96.616135,95.586174,99.626022,17.96,27690.000534,0.080291,10540.0,...,2.7200,1.062330e+11,1.119149e+11,1.921012e+11,7.560042e+10,1.189228,7.821093e+10,13.387247,36686784.0,17.660000
1,79.800,62.5000,92.200,100.000000,100.000000,100.000000,38.11,9449.999809,0.133868,2010.0,...,3.2900,4.785178e+09,6.856193e+09,1.370054e+10,3.817186e+10,4.019360,3.864383e+10,21.279306,2866376.0,44.520000
2,99.600,98.7000,100.000,99.697838,99.071304,99.933952,0.19,278029.998779,0.336716,6820.0,...,4.6300,4.523397e+10,5.632890e+10,1.036736e+11,4.916310e+11,1.200000,4.907023e+11,38.805186,41927007.0,68.019997
3,81.168,59.2630,93.575,84.048066,73.536247,94.733865,0.49,243760.104065,0.550819,23820.4,...,2.5561,4.360000e+08,6.620000e+08,1.677895e+10,9.545896e+11,2.671119,9.707024e+11,25.338415,48424.0,58.927900
4,49.100,8.1000,77.700,45.290001,7.333445,65.269997,57.36,75239.997864,0.111381,16220.0,...,5.2600,3.176775e+10,1.986966e+10,5.199370e+10,2.151179e+11,-1.316312,2.032423e+11,47.931542,31273533.0,21.620001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,55.394,32.2690,78.416,100.000000,100.000000,100.000000,3.43,226545.302620,0.161743,33739.7,...,3.3600,2.084000e+09,4.163000e+09,4.352000e+09,9.472831e+11,1.904762,9.697226e+11,13.940961,107001.0,93.419998
196,45.157,18.7335,70.111,100.000000,100.000000,100.000000,12.73,40982.100382,0.177872,23361.5,...,7.0800,2.598000e+09,9.023700e+09,1.804750e+10,2.886845e+10,1.227077,3.461983e+10,19.284126,4569087.0,69.739998
197,61.500,42.9000,93.700,62.000000,37.545254,87.139853,3.60,23860.000610,0.248813,4360.0,...,7.0700,1.308592e+09,9.344000e+09,3.643334e+10,8.711139e+11,0.752448,9.142263e+11,15.209188,30790513.0,45.299999
198,11.900,2.1000,24.600,40.317890,12.466436,76.461876,82.28,37560.001373,0.126504,10330.0,...,0.2500,9.987197e+09,9.717124e+09,1.517567e+10,6.110486e+10,4.034494,6.159734e+10,34.485322,17835893.0,24.860001
199,29.900,6.4000,79.100,45.572647,26.617121,85.468765,80.23,30829.999924,0.342751,6420.0,...,0.4400,8.936585e+09,9.695644e+09,3.008262e+10,3.611955e+10,5.009867,3.621026e+10,31.037898,15052184.0,32.650002

In [184]:
data_reduced.loc[:, num_variables] = filled

In [187]:
data_reduced

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE],...,Exports of goods and services (current US$) [NE.EXP.GNFS.CD],Imports of goods and services (current US$) [NE.IMP.GNFS.CD],Final consumption expenditure (current US$) [NE.CON.TOTL.CD],"GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]",GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],"GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]","Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]","Population, total [SP.POP.TOTL]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group
0,AFG,Afghanistan,30.900,13.8500,81.600,96.616135,95.586174,99.626022,17.96,27690.000534,...,1.062330e+11,1.119149e+11,1.921012e+11,7.560042e+10,1.189228,7.821093e+10,13.387247,36686784.0,17.660000,L
1,ALB,Albania,79.800,62.5000,92.200,100.000000,100.000000,100.000000,38.11,9449.999809,...,4.785178e+09,6.856193e+09,1.370054e+10,3.817186e+10,4.019360,3.864383e+10,21.279306,2866376.0,44.520000,UM
2,DZA,Algeria,99.600,98.7000,100.000,99.697838,99.071304,99.933952,0.19,278029.998779,...,4.523397e+10,5.632890e+10,1.036736e+11,4.916310e+11,1.200000,4.907023e+11,38.805186,41927007.0,68.019997,UM
3,ASM,American Samoa,81.168,59.2630,93.575,84.048066,73.536247,94.733865,0.49,243760.104065,...,4.360000e+08,6.620000e+08,1.677895e+10,9.545896e+11,2.671119,9.707024e+11,25.338415,48424.0,58.927900,UM
4,AGO,Angola,49.100,8.1000,77.700,45.290001,7.333445,65.269997,57.36,75239.997864,...,3.176775e+10,1.986966e+10,5.199370e+10,2.151179e+11,-1.316312,2.032423e+11,47.931542,31273533.0,21.620001,LM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,VIR,Virgin Islands (U.S.),55.394,32.2690,78.416,100.000000,100.000000,100.000000,3.43,226545.302620,...,2.084000e+09,4.163000e+09,4.352000e+09,9.472831e+11,1.904762,9.697226e+11,13.940961,107001.0,93.419998,H
196,PSE,West Bank and Gaza,45.157,18.7335,70.111,100.000000,100.000000,100.000000,12.73,40982.100382,...,2.598000e+09,9.023700e+09,1.804750e+10,2.886845e+10,1.227077,3.461983e+10,19.284126,4569087.0,69.739998,LM
197,YEM,"Yemen, Rep.",61.500,42.9000,93.700,62.000000,37.545254,87.139853,3.60,23860.000610,...,1.308592e+09,9.344000e+09,3.643334e+10,8.711139e+11,0.752448,9.142263e+11,15.209188,30790513.0,45.299999,L
198,ZMB,Zambia,11.900,2.1000,24.600,40.317890,12.466436,76.461876,82.28,37560.001373,...,9.987197e+09,9.717124e+09,1.517567e+10,6.110486e+10,4.034494,6.159734e+10,34.485322,17835893.0,24.860001,LM
199,ZWE,Zimbabwe,29.900,6.4000,79.100,45.572647,26.617121,85.468765,80.23,30829.999924,...,8.936585e+09,9.695644e+09,3.008262e+10,3.611955e+10,5.009867,3.621026e+10,31.037898,15052184.0,32.650002,LM

In [196]:
data_reduced.to_excel(r'C:\Users\isabe\OneDrive - Università degli Studi di Milano\second year\1st trimester\adv multivariate statistics\AMS\kaya identity analysis\data_reduce_filled.xlsx', index = False)

In [197]:
dudu = pd.read_excel("data_reduce_filled.xlsx")

In [198]:
dudu

,Country Code,Country Name,Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS],"Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]","Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]",Access to electricity (% of population) [EG.ELC.ACCS.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE],...,Exports of goods and services (current US$) [NE.EXP.GNFS.CD],Imports of goods and services (current US$) [NE.IMP.GNFS.CD],Final consumption expenditure (current US$) [NE.CON.TOTL.CD],"GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]",GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],"GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]","Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]","Population, total [SP.POP.TOTL]","Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]",Income Group
0,AFG,Afghanistan,30.900,13.8500,81.600,96.616135,95.586174,99.626022,17.96,27690.000534,...,1.062330e+11,1.119149e+11,1.921012e+11,7.560042e+10,1.189228,7.821093e+10,13.387247,36686784,17.660000,L
1,ALB,Albania,79.800,62.5000,92.200,100.000000,100.000000,100.000000,38.11,9449.999809,...,4.785178e+09,6.856193e+09,1.370054e+10,3.817186e+10,4.019360,3.864383e+10,21.279306,2866376,44.520000,UM
2,DZA,Algeria,99.600,98.7000,100.000,99.697838,99.071304,99.933952,0.19,278029.998779,...,4.523397e+10,5.632890e+10,1.036736e+11,4.916310e+11,1.200000,4.907023e+11,38.805186,41927007,68.019997,UM
3,ASM,American Samoa,81.168,59.2630,93.575,84.048066,73.536247,94.733865,0.49,243760.104065,...,4.360000e+08,6.620000e+08,1.677895e+10,9.545896e+11,2.671119,9.707024e+11,25.338415,48424,58.927900,UM
4,AGO,Angola,49.100,8.1000,77.700,45.290001,7.333445,65.269997,57.36,75239.997864,...,3.176775e+10,1.986966e+10,5.199370e+10,2.151179e+11,-1.316312,2.032423e+11,47.931542,31273533,21.620001,LM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,VIR,Virgin Islands (U.S.),55.394,32.2690,78.416,100.000000,100.000000,100.000000,3.43,226545.302620,...,2.084000e+09,4.163000e+09,4.352000e+09,9.472831e+11,1.904762,9.697226e+11,13.940961,107001,93.419998,H
196,PSE,West Bank and Gaza,45.157,18.7335,70.111,100.000000,100.000000,100.000000,12.73,40982.100382,...,2.598000e+09,9.023700e+09,1.804750e+10,2.886845e+10,1.227077,3.461983e+10,19.284126,4569087,69.739998,LM
197,YEM,"Yemen, Rep.",61.500,42.9000,93.700,62.000000,37.545254,87.139853,3.60,23860.000610,...,1.308592e+09,9.344000e+09,3.643334e+10,8.711139e+11,0.752448,9.142263e+11,15.209188,30790513,45.299999,L
198,ZMB,Zambia,11.900,2.1000,24.600,40.317890,12.466436,76.461876,82.28,37560.001373,...,9.987197e+09,9.717124e+09,1.517567e+10,6.110486e+10,4.034494,6.159734e+10,34.485322,17835893,24.860001,LM
199,ZWE,Zimbabwe,29.900,6.4000,79.100,45.572647,26.617121,85.468765,80.23,30829.999924,...,8.936585e+09,9.695644e+09,3.008262e+10,3.611955e+10,5.009867,3.621026e+10,31.037898,15052184,32.650002,LM

In [199]:
data_reduced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200 entries, 0 to 199
Data columns (total 29 columns):
 #   Column                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                 --------------  -----
 0   Country Code                                                                                           200 non-null    object
 1   Country Name                                                                                           200 non-null    object
 2   Access to clean fuels and technologies for cooking (% of population) [EG.CFT.ACCS.ZS]                  200 non-null    float64
 3   Access to clean fuels and technologies for cooking, rural (% of rural population) [EG.CFT.ACCS.RU.ZS]  200 non-null    float64
 4   Access to clean fuels and technologies for cooking, urban (% of urban population) [EG.CFT.ACCS.UR.ZS]  200 non-null    float64
 5   Access to electricity (% of population) [EG.ELC.ACCS.ZS]                                               200 non-null    float64
 6   Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]                               200 non-null    float64
 7   Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]                               200 non-null    float64
 8   Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]                    200 non-null    float64
 9   Total greenhouse gas emissions (kt of CO2 equivalent) [EN.ATM.GHGT.KT.CE]                              200 non-null    float64
 10  CO2 emissions (kg per 2017 PPP $ of GDP) [EN.ATM.CO2E.PP.GD.KD]                                        200 non-null    float64
 11  Agricultural methane emissions (thousand metric tons of CO2 equivalent) [EN.ATM.METH.AG.KT.CE]         200 non-null    float64
 12  Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.AG.KT.CE]   200 non-null    float64
 13  Methane emissions (kt of CO2 equivalent) [EN.ATM.METH.KT.CE]                                           200 non-null    float64
 14  Nitrous oxide emissions (thousand metric tons of CO2 equivalent) [EN.ATM.NOXE.KT.CE]                   200 non-null    float64
 15  Energy intensity level of primary energy (MJ/$2017 PPP GDP) [EG.EGY.PRIM.PP.KD]                        200 non-null    float64
 16  Carbon intensity of electricity (gCO2/kWh)                                                             200 non-null    float64
 17  Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]                               200 non-null    float64
 18  Employers, total (% of total employment) (modeled ILO estimate) [SL.EMP.MPYR.ZS]                       200 non-null    float64
 19  Exports of goods and services (current US$) [NE.EXP.GNFS.CD]                                           200 non-null    float64
 20  Imports of goods and services (current US$) [NE.IMP.GNFS.CD]                                           200 non-null    float64
 21  Final consumption expenditure (current US$) [NE.CON.TOTL.CD]                                           200 non-null    float64
 22  GDP, PPP (constant 2017 international $) [NY.GDP.MKTP.PP.KD]                                           200 non-null    float64
 23  GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]                                                              200 non-null    float64
 24  GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]                                                 200 non-null    float64
 25  Industry (including construction), value added (% of GDP) [NV.IND.TOTL.ZS]                             200 non-null    float64
 26  Population, total [SP.POP.TOTL]                                                                        200 non-null    float64
 27  Wage and salaried workers, total (% of total employment) (modeled ILO estimate) [SL.EMP.WORK.ZS]       200 non-null    float64
 28  Income Group                                                                                           200 non-null    category
dtypes: category(1), float64(26), object(2)
memory usage: 45.7+ KB